using System.Collections.Immutable;
using System.Diagnostics;
using System.IO.Compression;
using System.Reflection;
using System.Security;
using System.Xml.Linq;

using Microsoft.CodeAnalysis;

using NetAgents.Analyzers.Configuration;

namespace NetAgents.Analyzers.Tests.Packaging;

/// <summary>
/// Verifies the published package and its enforcement in real consumer builds.
/// </summary>
public sealed class PackageConsumptionTests
{
    private const string ValidSource = """
        namespace Consumer.Features;

        /// <summary>Provides the consumer entry point.</summary>
        public static class ExampleService
        {
            /// <summary>Returns the supplied recipient name.</summary>
            /// <param name="recipientName">The name to return.</param>
            /// <returns>The supplied name.</returns>
            public static string CreateGreeting(string recipientName)
            {
                return recipientName;
            }
        }
        """ + "\n";

    /// <summary>
    /// Verifies ordinary consumer builds apply code fixes without PATH, a shell, or manual targets.
    /// </summary>
    [Fact]
    public async Task PackageAutomaticallyFormatsWithoutShell()
    {
        DirectoryInfo workspace = Directory.CreateTempSubdirectory(prefix: "netagents automatic & consumer-");

        try
        {
            string packagePath = Environment.GetEnvironmentVariable(variable: "NETAGENTS_PACKAGE_PATH")
                ?? await PackAnalyzer(workspace.FullName);

            string version = VerifyPackageContents(packagePath);
            string projectPath = Path.Combine(workspace.FullName, path2: "Consumer.csproj");
            string sourceDirectory = Directory.CreateDirectory(Path.Combine(workspace.FullName, path2: "Features")).FullName;
            string sourcePath = Path.Combine(sourceDirectory, path2: "ExampleService.cs");
            string generatedPath = Path.Combine(sourceDirectory, path2: "Generated.g.cs");
            const string generatedSource = "// <auto-generated/>\ninternal class GeneratedThing{ }\n";

            string projectContent = $$"""
                <Project Sdk="Microsoft.NET.Sdk">
                  <PropertyGroup>
                    <TargetFramework>net10.0</TargetFramework>
                    <RootNamespace>CustomerApp</RootNamespace>
                    <ImplicitUsings>enable</ImplicitUsings>
                  </PropertyGroup>
                  <ItemGroup>
                    <PackageReference Include="NetAgents.Analyzers" Version="{{SecurityElement.Escape(version)}}" PrivateAssets="all" />
                  </ItemGroup>
                </Project>
                """;

            string sourceConfiguration = $$"""
                <configuration><packageSources><clear />
                <add key="local" value="{{SecurityElement.Escape(Path.GetDirectoryName(Path.GetFullPath(packagePath)))}}" />
                </packageSources></configuration>
                """;

            await File.WriteAllTextAsync(projectPath, projectContent);
            await File.WriteAllTextAsync(Path.Combine(workspace.FullName, path2: "NuGet.Config"), sourceConfiguration);
            await File.WriteAllTextAsync(generatedPath, generatedSource);

            string source = "using System.Text;\n" + ValidSource.Replace(oldValue: "string recipientName)", newValue: "\nstring recipientName\n)", StringComparison.Ordinal)
                .Replace(
                    oldValue: "return recipientName;",
                    newValue: "string greeting = string.Concat(\nrecipientName,\nstring.Empty\n);\nif (string.IsNullOrEmpty(greeting)) { System.Console.WriteLine(greeting); }\nreturn greeting;",
                    StringComparison.Ordinal
                );

            source = source.Replace(
                oldValue: "    /// <summary>Returns the supplied recipient name.</summary>",
                newValue: "    /// <summary>Runs the final action.</summary>\n    public static void ZebraAction() {}\n    /// <summary>Runs the first action.</summary>\n    public static void AlphaAction() {}\n    /// <summary>Returns the supplied recipient name.</summary>",
                StringComparison.Ordinal
            );

            await File.WriteAllTextAsync(sourcePath, source);
            await RunDevelopmentKit(workspace.FullName, ["restore", projectPath, "--packages", Path.Combine(workspace.FullName, path2: "packages")]);
            string[] buildArguments = ["build", projectPath, "--no-restore", "--nologo", "--verbosity", "quiet"];

            await RunDevelopmentKit(workspace.FullName, buildArguments, withoutShell: true);
            string formatted = await File.ReadAllTextAsync(sourcePath);
            Assert.Contains(expectedSubstring: "namespace CustomerApp.Features;", formatted, StringComparison.Ordinal);
            Assert.Contains(expectedSubstring: "CreateGreeting(string recipientName)", formatted, StringComparison.Ordinal);
            Assert.True(
                formatted.IndexOf(value: "AlphaAction", StringComparison.Ordinal) < formatted.IndexOf(value: "ZebraAction", StringComparison.Ordinal)
            );
            Assert.Contains(expectedSubstring: "}\n\n    /// <summary>Returns", formatted, StringComparison.Ordinal);
            Assert.Contains(expectedSubstring: "string.Concat(recipientName, string.Empty)", formatted, StringComparison.Ordinal);
            Assert.DoesNotContain(expectedSubstring: "using System.Text;", formatted, StringComparison.Ordinal);
            Assert.Equal(generatedSource, await File.ReadAllTextAsync(generatedPath));
            DateTime modification = File.GetLastWriteTimeUtc(sourcePath);
            await RunDevelopmentKit(workspace.FullName, buildArguments, withoutShell: true);
            Assert.Equal(formatted, await File.ReadAllTextAsync(sourcePath));
            Assert.Equal(modification, File.GetLastWriteTimeUtc(sourcePath));

            string conditionalAssignments = ValidSource
                .Replace(
                    oldValue: "<param name=\"recipientName\">The name to return.</param>",
                    newValue: "<param name=\"builder\">The optional builder.</param>\n    /// <param name=\"length\">The required length.</param>",
                    StringComparison.Ordinal
                )
                .Replace(oldValue: "    /// <returns>The supplied name.</returns>\n", string.Empty, StringComparison.Ordinal)
                .Replace(
                    oldValue: "string CreateGreeting(string recipientName)",
                    newValue: "void UpdateLength(System.Text.StringBuilder? builder, int length)",
                    StringComparison.Ordinal
                )
                .Replace(
                    oldValue: "return recipientName;",
                    newValue: "if (builder is not null)\n            builder.Length = length;\n        if (builder is not null)\n            builder.Capacity = length;",
                    StringComparison.Ordinal
                );

            await File.WriteAllTextAsync(sourcePath, conditionalAssignments);
            await RunDevelopmentKit(workspace.FullName, buildArguments, withoutShell: true);
            string simplifiedAssignments = await File.ReadAllTextAsync(sourcePath);
            Assert.Contains(expectedSubstring: "builder?.Length = length;", simplifiedAssignments, StringComparison.Ordinal);
            Assert.Contains(expectedSubstring: "builder?.Capacity = length;", simplifiedAssignments, StringComparison.Ordinal);
            await RunDevelopmentKit(workspace.FullName, buildArguments, withoutShell: true);
            Assert.Equal(simplifiedAssignments, await File.ReadAllTextAsync(sourcePath));

            string argumentNames = ValidSource.Replace(
                oldValue: "return recipientName;",
                newValue: "string padded = string.Empty.PadLeft(totalWidth: 4, ' ');\n\n        return string.Concat(str0: padded, recipientName);",
                StringComparison.Ordinal
            );

            await File.WriteAllTextAsync(sourcePath, argumentNames);
            await RunDevelopmentKit(workspace.FullName, buildArguments, withoutShell: true);
            string namedArguments = await File.ReadAllTextAsync(sourcePath);
            Assert.Contains(expectedSubstring: "PadLeft(totalWidth: 4, paddingChar: ' ')", namedArguments, StringComparison.Ordinal);
            Assert.Contains(expectedSubstring: "string.Concat(padded, recipientName)", namedArguments, StringComparison.Ordinal);
            await RunDevelopmentKit(workspace.FullName, buildArguments, withoutShell: true);
            Assert.Equal(namedArguments, await File.ReadAllTextAsync(sourcePath));

            const string tupleMethod = """
                    private static (int X, int Y) ResolveCoordinates() => (1, 2);

                    private static int SubtractCoordinates()
                    {
                        var firstPosition = ResolveCoordinates();
                        var secondPosition = ResolveCoordinates();
                        return firstPosition.X - secondPosition.X + firstPosition.Y - secondPosition.Y;
                    }

                    /// <summary>Resolves habitat bounds.</summary>
                    /// <param name="recipientName">The habitat name.</param>
                    /// <returns>The habitat and its dimensions.</returns>
                    internal static (string Habitat, int Width, int Height) Resolve(string recipientName)
                    {
                        return (recipientName, recipientName.Length, recipientName.Length);
                    }

                """;

            string tupleSource = ValidSource
                .Replace(
                    oldValue: "    /// <summary>Returns the supplied recipient name.</summary>",
                    tupleMethod + "    /// <summary>Returns the supplied recipient name.</summary>",
                    StringComparison.Ordinal
                )
                .Replace(
                    oldValue: "return recipientName;",
                    newValue: "System.ArgumentNullException.ThrowIfNull(recipientName);\nvar bounds = Resolve(recipientName);\nvar habitat = bounds.Habitat;\nvar width = bounds.Width;\nvar height = bounds.Height;\nvar habitatValue = string.Empty;\nvar coordinateOffset = SubtractCoordinates();\nreturn string.Concat(habitat, habitatValue, new string(c: ' ', width + height + coordinateOffset));",
                    StringComparison.Ordinal
                );

            await File.WriteAllTextAsync(sourcePath, tupleSource);
            await RunDevelopmentKit(workspace.FullName, buildArguments, withoutShell: true);
            string renamedTuple = await File.ReadAllTextAsync(sourcePath);
            Assert.Contains(
                expectedSubstring: "(string Habitat, int Width, int Height) bounds = Resolve(recipientName);",
                renamedTuple,
                StringComparison.Ordinal
            );
            Assert.Contains(expectedSubstring: "string habitat = bounds.Habitat;", renamedTuple, StringComparison.Ordinal);
            Assert.Contains(expectedSubstring: "int width = bounds.Width;", renamedTuple, StringComparison.Ordinal);
            Assert.Contains(expectedSubstring: "int height = bounds.Height;", renamedTuple, StringComparison.Ordinal);
            Assert.Contains(expectedSubstring: "(int X, int Y) firstPosition = ResolveCoordinates();", renamedTuple, StringComparison.Ordinal);
            Assert.Contains(expectedSubstring: "(int X, int Y) secondPosition = ResolveCoordinates();", renamedTuple, StringComparison.Ordinal);
            Assert.DoesNotContain(expectedSubstring: "(int x, int y)", renamedTuple, StringComparison.Ordinal);
            await RunDevelopmentKit(workspace.FullName, buildArguments, withoutShell: true);
            Assert.Equal(renamedTuple, await File.ReadAllTextAsync(sourcePath));

            string manyTupleMethods = string.Join(
                Environment.NewLine,
                Enumerable.Range(start: 0, count: 70).Select(
                    static index => $$"""
                        internal static (string Habitat, int Width, int Height) ResolveBounds{{index}}(string value) =>
                            (value, value.Length, value.Length);

                        private static string ConsumeBounds{{index}}(string value)
                        {
                            var bounds = ResolveBounds{{index}}(value);
                            var habitat = bounds.Habitat;
                            var width = bounds.Width;
                            var height = bounds.Height;
                            return string.Concat(habitat, new string(c: ' ', width + height));
                        }
                    """
                )
            );

            string manyTupleSource = ValidSource.Replace(oldValue: "    }\n}\n", $"    }}\n\n{manyTupleMethods}\n}}\n", StringComparison.Ordinal);
            await File.WriteAllTextAsync(sourcePath, manyTupleSource);
            await RunDevelopmentKit(workspace.FullName, buildArguments, withoutShell: true);
            string renamedManyTuples = await File.ReadAllTextAsync(sourcePath);
            await RunDevelopmentKit(workspace.FullName, buildArguments, withoutShell: true);
            Assert.Equal(renamedManyTuples, await File.ReadAllTextAsync(sourcePath));

            string longName = new(c: 'p', count: 130);

            string longSource = ValidSource.Replace(oldValue: "return recipientName;", newValue: "return string.Concat(recipientName, string.Empty);", StringComparison.Ordinal)
                .Replace(oldValue: "recipientName", longName, StringComparison.Ordinal);

            await File.WriteAllTextAsync(sourcePath, longSource);
            await RunDevelopmentKit(workspace.FullName, buildArguments, withoutShell: true);
            string expanded = await File.ReadAllTextAsync(sourcePath);
            Assert.Contains(expectedSubstring: "CreateGreeting(\n", expanded, StringComparison.Ordinal);
            Assert.Contains(expectedSubstring: "string.Concat(\n", expanded, StringComparison.Ordinal);

            // An unresolved symbol stays a compiler error: no generated declaration, no formatting failure.
            string unresolvedSource = ValidSource.Replace(
                oldValue: "return recipientName;",
                newValue: "System.Console.WriteLine(payload);\n\n        return recipientName;",
                StringComparison.Ordinal
            );

            // Unrelated fixes still apply, so the expectation is the namespace repair and nothing else.
            string expectedUnresolved = unresolvedSource.Replace(oldValue: "namespace Consumer.Features;", newValue: "namespace CustomerApp.Features;", StringComparison.Ordinal);

            await File.WriteAllTextAsync(sourcePath, unresolvedSource);
            await RunDevelopmentKit(workspace.FullName, buildArguments, expectedDiagnosticIdentifier: "CS0103", withoutShell: true);
            Assert.Equal(expectedUnresolved, await File.ReadAllTextAsync(sourcePath));

            // Formatting runs before compilation, so a build that fails afterwards still rewrites the
            // file. The log names every rewritten path so a dirty tree is never a surprise (#11).
            string relativeSourcePath = Path.Combine(path1: "Features", path2: "ExampleService.cs");
            string[] reportingArguments = ["build", projectPath, "--no-restore", "--nologo", "--verbosity", "minimal"];

            await File.WriteAllTextAsync(sourcePath, source);
            await RunDevelopmentKit(workspace.FullName, reportingArguments, expectedOutput: ["NetAgents rewrote " + relativeSourcePath], withoutShell: true);

            // A rebuild that changes nothing stays silent.
            await RunDevelopmentKit(workspace.FullName, reportingArguments, forbiddenOutput: ["NetAgents rewrote"], withoutShell: true);

            string blockedSource = ValidSource.Replace(
                oldValue: "return recipientName;",
                newValue: "recipientName.Trim();\n\n        return string.Concat(\nrecipientName,\nstring.Empty\n);",
                StringComparison.Ordinal
            );

            await File.WriteAllTextAsync(sourcePath, blockedSource);
            await RunDevelopmentKit(
                workspace.FullName,
                reportingArguments,
                expectedDiagnosticIdentifier: "NETAGENTS0015",
                expectedOutput: ["NetAgents rewrote " + relativeSourcePath, "NetAgents rewrote 1 file before this build failed on diagnostics no fix repairs: NETAGENTS0015", "NETAGENTS0015"],
                withoutShell: true
            );

            // The failing build kept its rewrite, which is why the report has to name it.
            Assert.Contains(
                expectedSubstring: "string.Concat(recipientName, string.Empty)",
                await File.ReadAllTextAsync(sourcePath),
                StringComparison.Ordinal
            );

            await File.WriteAllTextAsync(sourcePath, source);
            await RunDevelopmentKit(
                workspace.FullName,
                arguments: ["msbuild", projectPath, "-t:FormatNetAgentsConsumerSource", "-p:DesignTimeBuild=true"],
                withoutShell: true
            );
            Assert.Equal(source, await File.ReadAllTextAsync(sourcePath));

            string multiTargetProject = projectContent.Replace(
                oldValue: "<TargetFramework>net10.0</TargetFramework>",
                newValue: "<TargetFrameworks>net10.0;net10.0-windows</TargetFrameworks>",
                StringComparison.Ordinal
            );

            string conditionalSource = ValidSource.Replace(
                oldValue: "return recipientName;",
                newValue: "\n#if WINDOWS\nreturn string.Concat(\nrecipientName,\nstring.Empty\n);\n#else\nreturn string.Concat(\nrecipientName,\nstring.Empty\n);\n#endif",
                StringComparison.Ordinal
            );

            await File.WriteAllTextAsync(projectPath, multiTargetProject);
            await File.WriteAllTextAsync(sourcePath, conditionalSource);
            await RunDevelopmentKit(workspace.FullName, ["restore", projectPath, "--packages", Path.Combine(workspace.FullName, path2: "packages")]);
            await RunDevelopmentKit(workspace.FullName, buildArguments, withoutShell: true);
            string multiTargetSource = await File.ReadAllTextAsync(sourcePath);
            Assert.Equal(expected: 3, multiTargetSource.Split(separator: "string.Concat(recipientName, string.Empty)", StringSplitOptions.None).Length);
            Assert.True(File.Exists(Path.Combine(workspace.FullName, path2: "bin/Debug/net10.0/Consumer.dll")));
            Assert.True(File.Exists(Path.Combine(workspace.FullName, path2: "bin/Debug/net10.0-windows/Consumer.dll")));

            await File.WriteAllTextAsync(
                sourcePath,
                ValidSource.Replace(
                    oldValue: "string CreateGreeting(string recipientName)",
                    newValue: "System.IComparable CreateGreeting(int recipientName)",
                    StringComparison.Ordinal
                )
            );
            await RunDevelopmentKit(workspace.FullName, buildArguments, expectedDiagnosticIdentifier: "NETAGENTS0001", withoutShell: true);
        }
        finally
        {
            workspace.Delete(recursive: true);
        }
    }

    /// <summary>
    /// Verifies SDK defaults, consumer diagnostics, and rejected policy overrides.
    /// </summary>
    [Fact]
    public async Task PackageEnforcesPolicyInConsumerBuilds()
    {
        DirectoryInfo workspace = Directory.CreateTempSubdirectory(prefix: "netagents-package-consumer-");

        try
        {
            string packagePath = Environment.GetEnvironmentVariable(variable: "NETAGENTS_PACKAGE_PATH")
                ?? await PackAnalyzer(workspace.FullName);

            packagePath = Path.GetFullPath(packagePath);
            string packageVersion = VerifyPackageContents(packagePath);
            await VerifyConfigurationMatchesTemplate(workspace.FullName, packagePath);
            string projectPath = Path.Combine(paths: [workspace.FullName, "Consumer.csproj"]);
            string sourcePath = Path.Combine(paths: [workspace.FullName, "ExampleService.cs"]);

            string projectContent = $$"""
                <Project Sdk="Microsoft.NET.Sdk">
                  <PropertyGroup>
                    <TargetFramework>net10.0</TargetFramework>
                    <ImplicitUsings>enable</ImplicitUsings>
                  </PropertyGroup>
                  <ItemGroup>
                    <PackageReference Include="NetAgents.Analyzers" Version="{{SecurityElement.Escape(packageVersion)}}" PrivateAssets="all" />
                  </ItemGroup>
                </Project>
                """;

            await File.WriteAllTextAsync(projectPath, projectContent);
            await File.WriteAllTextAsync(sourcePath, ValidSource);

            string packageDirectory = Path.GetDirectoryName(packagePath)
                ?? throw new InvalidOperationException(message: "The package directory is missing.");

            string sourceConfiguration = $$"""
                <configuration>
                  <packageSources>
                    <clear />
                    <add key="local" value="{{SecurityElement.Escape(packageDirectory)}}" />
                  </packageSources>
                </configuration>
                """;

            await File.WriteAllTextAsync(Path.Combine(paths: [workspace.FullName, "NuGet.Config"]), sourceConfiguration);
            await RunDevelopmentKit(workspace.FullName, ["restore", projectPath, "--packages", Path.Combine(paths: [workspace.FullName, "packages"])]);

            // Formatting always runs, so these cases cover the violations no code fix can repair.
            string[] buildArguments = ["build", projectPath, "--no-restore", "--nologo", "--verbosity", "quiet"];
            await RunDevelopmentKit(workspace.FullName, buildArguments);
            await VerifyDirectoryLimit(workspace.FullName, buildArguments);

            // Repairable violations are covered by the automatic formatting test; this one keeps the
            // cases that survive every available fix, so a clean build proves nothing was left unenforced.
            await RunDevelopmentKit(workspace.FullName, ["format", projectPath, "--no-restore", "--verify-no-changes"]);

            string lookupSource = ValidSource.Replace(
                oldValue: "return recipientName;",
                "System.Collections.Generic.Dictionary<string, string> values = [];\n\n"
                    + "        return values.TryGetValue(recipientName, out string? greeting) ? greeting : recipientName;",
                StringComparison.Ordinal
            );

            await File.WriteAllTextAsync(sourcePath, lookupSource);
            await RunDevelopmentKit(workspace.FullName, buildArguments);

            string[] ignoredLookups =
            [
                "values.TryGetValue(recipientName, out string? greeting);",
                "_ = values.TryGetValue(recipientName, out string? greeting);",
            ];

            foreach (string ignoredLookup in ignoredLookups)
            {
                string ignoredSource = lookupSource.Replace(
                    oldValue: "return values.TryGetValue(recipientName, out string? greeting) ? greeting : recipientName;",
                    ignoredLookup + "\n\n        return greeting ?? recipientName;",
                    StringComparison.Ordinal
                );

                await File.WriteAllTextAsync(sourcePath, ignoredSource);
                await RunDevelopmentKit(workspace.FullName, buildArguments, expectedDiagnosticIdentifier: "NETAGENTS0015");
                await File.WriteAllTextAsync(sourcePath, "#pragma warning disable NETAGENTS0015\n" + ignoredSource);
                await RunDevelopmentKit(workspace.FullName, buildArguments, expectedDiagnosticIdentifier: "NETAGENTS0015");
            }

            await VerifyDiscardAssignments(workspace.FullName, sourcePath, buildArguments);

            string boxingSource = ValidSource.Replace(
                oldValue: "string CreateGreeting(string recipientName)",
                newValue: "System.IComparable CreateGreeting(int recipientName)",
                StringComparison.Ordinal
            );

            await File.WriteAllTextAsync(sourcePath, boxingSource);
            await RunDevelopmentKit(workspace.FullName, buildArguments, expectedDiagnosticIdentifier: "NETAGENTS0001");
            await File.WriteAllTextAsync(sourcePath, "#pragma warning disable NETAGENTS0001\n" + boxingSource);
            await RunDevelopmentKit(workspace.FullName, buildArguments, expectedDiagnosticIdentifier: "NETAGENTS0001");
            await File.WriteAllTextAsync(
                sourcePath,
                ValidSource.Replace(oldValue: "/// <summary>Provides the consumer entry point.</summary>\n", string.Empty, StringComparison.Ordinal)
            );
            await RunDevelopmentKit(workspace.FullName, buildArguments, expectedDiagnosticIdentifier: "CS1591");
            await File.WriteAllTextAsync(sourcePath, ValidSource);

            string editorConfigurationPath = Path.Combine(paths: [workspace.FullName, ".editorconfig"]);

            string[] conflictingEditorSettings =
            [
                "csharp_style_var_elsewhere = true:silent",
                "csharp_prefer_braces = true:silent",
                "insert_final_newline = false",
                "dotnet_diagnostic.NETAGENTS0001.severity = none",
                "dotnet_diagnostic.NETAGENTS0015.severity = none",
                "dotnet_diagnostic.NETAGENTS0017.severity = none",
                "dotnet_diagnostic.NETAGENTS0018.severity = none",
                "dotnet_diagnostic.IDE0005.severity = none",
                "dotnet_diagnostic.IDE0059.severity = none",
                "dotnet_diagnostic.CS1591.severity = none",
            ];

            foreach (string conflictingSetting in conflictingEditorSettings)
            {
                await File.WriteAllTextAsync(editorConfigurationPath, $"root = true\n[*.cs]\n{conflictingSetting}\n");
                await RunDevelopmentKit(workspace.FullName, buildArguments, expectedDiagnosticIdentifier: "NETAGENTS0013");
            }

            File.Delete(editorConfigurationPath);

            string[] conflictingProjectSettings =
            [
                "<Nullable>disable</Nullable>",
                "<AnalysisLevel>none</AnalysisLevel>",
                "<AnalysisMode>Minimum</AnalysisMode>",
                "<AnalysisLevelStyle>none</AnalysisLevelStyle>",
                "<AnalysisModeStyle>None</AnalysisModeStyle>",
                "<CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>",
                "<EnableCodeStyleSeverity>false</EnableCodeStyleSeverity>",
                "<EnableNETAnalyzers>false</EnableNETAnalyzers>",
                "<RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>",
                "<TreatWarningsAsErrors>false</TreatWarningsAsErrors>",
                "<GenerateDocumentationFile>false</GenerateDocumentationFile>",
                "<WarningsAsErrors>CS0168</WarningsAsErrors>",
                "<EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>",
            ];

            foreach (string conflictingSetting in conflictingProjectSettings)
            {
                await File.WriteAllTextAsync(
                    projectPath,
                    projectContent.Replace(
                        oldValue: "<ImplicitUsings>enable</ImplicitUsings>",
                        $"<ImplicitUsings>enable</ImplicitUsings>{conflictingSetting}",
                        StringComparison.Ordinal
                    )
                );
                await RunDevelopmentKit(workspace.FullName, buildArguments, expectedDiagnosticIdentifier: "NETAGENTS0014");
            }

            await File.WriteAllTextAsync(projectPath, projectContent);

            string[] conflictingBuildArguments =
            [
                "-p:RunAnalyzers=false",
                "-p:CodeAnalysisTreatWarningsAsErrors=false",
                "-p:GenerateDocumentationFile=false",
                "-p:SkipGlobalAnalyzerConfigForPackage=true",
                "-p:NoWarn=NETAGENTS0001",
                "-p:NoWarn=NETAGENTS0015",
                "-p:NoWarn=1591",
                "-p:WarningsNotAsErrors=CS1591",
                "-p:NoWarn=IDE0005",
                "-p:WarningsNotAsErrors=CA1311",
            ];

            foreach (string conflictingArgument in conflictingBuildArguments)
                await RunDevelopmentKit(workspace.FullName, [.. buildArguments, conflictingArgument], expectedDiagnosticIdentifier: "NETAGENTS0014");

            // A newer SDK asks for a language version this package's Roslyn cannot parse, and the
            // compiler, not the formatter, owns whether that version exists.
            await RunDevelopmentKit(
                workspace.FullName,
                [.. buildArguments, "-p:LangVersion=15.0"],
                expectedDiagnosticIdentifier: "CS1617",
                forbiddenOutput: ["NetAgents automatic formatting failed"]
            );

            await RunDevelopmentKit(workspace.FullName, buildArguments);
        }
        finally
        {
            workspace.Delete(recursive: true);
        }
    }

    private static async Task<string> PackAnalyzer(string workspacePath)
    {
        DirectoryInfo? repositoryDirectory = new(AppContext.BaseDirectory);

        while (repositoryDirectory is not null && !File.Exists(Path.Combine(paths: [repositoryDirectory.FullName, "NetAgents.slnx"])))
            repositoryDirectory = repositoryDirectory.Parent;

        Assert.NotNull(repositoryDirectory);

        string configuration = typeof(PackageConsumptionTests).Assembly
            .GetCustomAttribute<AssemblyConfigurationAttribute>()?.Configuration
            ?? throw new InvalidOperationException(message: "The test build configuration is missing.");

        string packageDirectory = Path.Combine(paths: [workspacePath, "artifacts"]);
        await RunDevelopmentKit(
            repositoryDirectory.FullName,
                    [
            "pack", "src/NetAgents.Analyzers.csproj", "--configuration", configuration,
            "--no-build", "--no-restore", "--output", packageDirectory,
        ]
        ).ConfigureAwait(continueOnCapturedContext: false);

        return Assert.Single(Directory.EnumerateFiles(packageDirectory, searchPattern: "*.nupkg"));
    }

    private static async Task RunDevelopmentKit(
        string workingDirectory,
        string[] arguments,
        string? expectedDiagnosticIdentifier = null,
        string[]? expectedOutput = null,
        string[]? forbiddenOutput = null,
        bool withoutShell = false
    )
    {
        using Process process = new();

        process.StartInfo = new ProcessStartInfo
        {
            FileName = Environment.GetEnvironmentVariable(variable: "DOTNET_HOST_PATH") ?? "dotnet",
            WorkingDirectory = workingDirectory,
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
        };

        // Reused MSBuild workers retain redirected pipes after the command exits.
        process.StartInfo.Environment[key: "MSBUILDDISABLENODEREUSE"] = "1";

        foreach (string argument in arguments)
            process.StartInfo.ArgumentList.Add(argument);

        if (withoutShell)
        {
            process.StartInfo.Environment[key: "PATH"] = string.Empty;
            process.StartInfo.Environment[key: "SHELL"] = "/no-shell";
            process.StartInfo.Environment[key: "COMSPEC"] = "/no-shell";
        }

        Assert.True(process.Start());
        Task<string> standardOutput = process.StandardOutput.ReadToEndAsync();
        Task<string> standardError = process.StandardError.ReadToEndAsync();

        try
        {
            await process.WaitForExitAsync().WaitAsync(TimeSpan.FromMinutes(minutes: 2)).ConfigureAwait(continueOnCapturedContext: false);
        }
        catch (TimeoutException)
        {
            process.Kill(entireProcessTree: true);
            await process.WaitForExitAsync().ConfigureAwait(continueOnCapturedContext: false);

            throw;
        }

        string output = await standardOutput.ConfigureAwait(continueOnCapturedContext: false) + await standardError.ConfigureAwait(continueOnCapturedContext: false);
        Assert.DoesNotContain(expectedSubstring: "AD0001", output, StringComparison.Ordinal);

        // A formatting fault must reach the log as a build error instead of aborting the task.
        Assert.DoesNotContain(expectedSubstring: "MSB4018", output, StringComparison.Ordinal);

        foreach (string expected in expectedOutput ?? [])
            Assert.Contains(expected, output, StringComparison.Ordinal);

        foreach (string forbidden in forbiddenOutput ?? [])
            Assert.DoesNotContain(forbidden, output, StringComparison.Ordinal);

        if (expectedDiagnosticIdentifier is null)
        {
            Assert.True(process.ExitCode == 0, output);
        }
        else
        {
            Assert.True(process.ExitCode != 0, output);
            Assert.Contains(expectedDiagnosticIdentifier, output, StringComparison.Ordinal);
        }
    }

    private static async Task VerifyConfigurationMatchesTemplate(string workspacePath, string packagePath)
    {
        string templateDirectory = Path.Combine(paths: [workspacePath, "microsoft-defaults"]);
        await RunDevelopmentKit(workspacePath, ["new", "editorconfig", "--output", templateDirectory])
            .ConfigureAwait(continueOnCapturedContext: false);
        string templatePath = Path.Combine(paths: [templateDirectory, ".editorconfig"]);
        string template = await File.ReadAllTextAsync(templatePath).ConfigureAwait(continueOnCapturedContext: false);
        AnalyzerConfig[] templateConfigurations = [AnalyzerConfig.Parse(template, templatePath)];

        AnalyzerConfigOptionsResult templateOptions = AnalyzerConfigSet.Create(templateConfigurations)
            .GetOptionsForSourcePath(Path.Combine(paths: [templateDirectory, "ExampleService.cs"]));

        Assert.NotEmpty(templateOptions.AnalyzerOptions);

        using Stream embeddedStream = typeof(ConfigurationPolicyAnalyzer).Assembly.GetManifestResourceStream(name: "NetAgents.Analyzers.Configuration.NetAgents.globalconfig")
            ?? throw new InvalidOperationException(message: "The embedded configuration is missing.");

        using StreamReader embeddedReader = new(embeddedStream);

        string embeddedConfiguration = await embeddedReader.ReadToEndAsync().ConfigureAwait(continueOnCapturedContext: false);

        // One global config must not define a key twice; the effective value would depend on parse order.
        List<string> configurationKeys = [];

        foreach (string line in embeddedConfiguration.Split(separator: '\n'))
        {
            int separatorIndex = line.IndexOf(value: '=', StringComparison.Ordinal);

            if (separatorIndex > 0)
                configurationKeys.Add(line[..separatorIndex].Trim());
        }

        Assert.Equal(configurationKeys.Count, configurationKeys.Distinct(StringComparer.OrdinalIgnoreCase).Count());

        ZipArchive package = await ZipFile.OpenReadAsync(packagePath).ConfigureAwait(continueOnCapturedContext: false);

        await using (package.ConfigureAwait(continueOnCapturedContext: false))
        {
            ZipArchiveEntry configurationEntry = package.GetEntry(entryName: "buildTransitive/NetAgents.globalconfig")
                ?? throw new InvalidOperationException(message: "The packaged configuration is missing.");

            using StreamReader packagedReader = new(await configurationEntry.OpenAsync().ConfigureAwait(continueOnCapturedContext: false));

            Assert.Equal(embeddedConfiguration, await packagedReader.ReadToEndAsync().ConfigureAwait(continueOnCapturedContext: false));
        }

        AnalyzerConfig[] generatedConfigurations =
        [
            AnalyzerConfig.Parse(embeddedConfiguration, Path.Combine(paths: [templateDirectory, "NetAgents.globalconfig"])),
        ];

        AnalyzerConfigSet generatedConfiguration = AnalyzerConfigSet.Create(generatedConfigurations, out ImmutableArray<Diagnostic> diagnostics);
        Assert.True(diagnostics.IsEmpty);

        // A source outside the configuration's directory must still receive every C# default.
        AnalyzerConfigOptionsResult generatedOptions = generatedConfiguration
            .GetOptionsForSourcePath(Path.Combine(paths: [workspacePath, "Unrelated", "ExampleService.cs"]));

        Assert.True(generatedOptions.Diagnostics.IsEmpty);

        foreach (KeyValuePair<string, string> preference in templateOptions.AnalyzerOptions)
        {
            // Preserve policy overrides while following the SDK's formatting preferences.
            string expectedValue = preference.Key switch
            {
                "insert_final_newline" => "true",
                "dotnet_naming_symbols.type_parameters.applicable_kinds" when preference.Value == "namespace" => "type_parameter",
                "csharp_style_unused_value_assignment_preference" => preference.Value.Split(separator: ':').First() + ":error",
                "csharp_prefer_braces" => "false:silent",
                _ => preference.Value,
            };

            Assert.Equal(expectedValue, generatedOptions.AnalyzerOptions[preference.Key]);
        }
    }

    private static async Task VerifyDirectoryLimit(string workspacePath, string[] buildArguments)
    {
        string directory = Directory.CreateDirectory(Path.Combine(workspacePath, path2: "Features")).FullName;

        for (int index = 0; index < 16; index++)
        {
            string fileName = "Component" + index.ToString(format: "D2", System.Globalization.CultureInfo.InvariantCulture) + ".cs";
            await File.WriteAllTextAsync(Path.Combine(directory, fileName), contents: "// Authored source.\n").ConfigureAwait(continueOnCapturedContext: false);
        }

        await File.WriteAllTextAsync(Path.Combine(directory, path2: "Generated.g.cs"), contents: "// Generated source.\n").ConfigureAwait(continueOnCapturedContext: false);
        await File.WriteAllTextAsync(Path.Combine(directory, path2: "GeneratedHeader.cs"), contents: "// <auto-generated/>\n").ConfigureAwait(continueOnCapturedContext: false);
        await File.WriteAllTextAsync(Path.Combine(directory, path2: "Notes.txt"), contents: "Directory notes.\n").ConfigureAwait(continueOnCapturedContext: false);
        string childDirectory = Directory.CreateDirectory(Path.Combine(directory, path2: "Purchasing")).FullName;
        await File.WriteAllTextAsync(Path.Combine(childDirectory, path2: "NestedComponent.cs"), contents: "// Authored source.\n").ConfigureAwait(continueOnCapturedContext: false);
        await RunDevelopmentKit(workspacePath, buildArguments).ConfigureAwait(continueOnCapturedContext: false);

        string excessFile = Path.Combine(directory, path2: "Component16.cs");
        await File.WriteAllTextAsync(excessFile, contents: "// Authored source.\n").ConfigureAwait(continueOnCapturedContext: false);
        await RunDevelopmentKit(workspacePath, buildArguments, expectedDiagnosticIdentifier: "NETAGENTS0018").ConfigureAwait(continueOnCapturedContext: false);
        await File.WriteAllTextAsync(Path.Combine(directory, path2: "Component00.cs"), contents: "#pragma warning disable NETAGENTS0018\n").ConfigureAwait(continueOnCapturedContext: false);
        await RunDevelopmentKit(workspacePath, buildArguments, expectedDiagnosticIdentifier: "NETAGENTS0018").ConfigureAwait(continueOnCapturedContext: false);
        File.Move(excessFile, Path.Combine(childDirectory, path2: "Component16.cs"));
        await RunDevelopmentKit(workspacePath, buildArguments).ConfigureAwait(continueOnCapturedContext: false);
        Directory.Delete(directory, recursive: true);
    }

    private static async Task VerifyDiscardAssignments(string workspacePath, string sourcePath, string[] buildArguments)
    {
        string[] discardedValues =
        [
            "_ = 42;",
            "_ = recipientName;",
            "_ = recipientName?.Length;",
            "_ = new System.Text.StringBuilder();",
            "System.Action<string> consume = _ => _ = string.Empty;\n\n        consume(recipientName);",
        ];

        foreach (string discardedValue in discardedValues)
        {
            string source = ValidSource.Replace(oldValue: "return recipientName;", discardedValue + "\n\n        return recipientName;", StringComparison.Ordinal);
            await File.WriteAllTextAsync(sourcePath, source).ConfigureAwait(continueOnCapturedContext: false);
            await RunDevelopmentKit(workspacePath, buildArguments, expectedDiagnosticIdentifier: "NETAGENTS0015").ConfigureAwait(continueOnCapturedContext: false);
        }

        string discardedLoop = ValidSource.Replace(
            oldValue: "return recipientName;",
            "(string First, string Second)[] greetings = [(recipientName, string.Empty)];\n\n"
                + "        foreach ((string greeting, string _) in greetings)\n            recipientName = greeting;\n\n        return recipientName;",
            StringComparison.Ordinal
        );

        await File.WriteAllTextAsync(sourcePath, discardedLoop).ConfigureAwait(continueOnCapturedContext: false);
        await RunDevelopmentKit(workspacePath, buildArguments, expectedDiagnosticIdentifier: "NETAGENTS0015").ConfigureAwait(continueOnCapturedContext: false);

        string consumedLoop = discardedLoop.Replace(oldValue: "string _)", newValue: "string suffix)", StringComparison.Ordinal)
            .Replace(oldValue: "recipientName = greeting;", newValue: "recipientName = greeting + suffix;", StringComparison.Ordinal);

        await File.WriteAllTextAsync(sourcePath, consumedLoop).ConfigureAwait(continueOnCapturedContext: false);
        await RunDevelopmentKit(workspacePath, buildArguments).ConfigureAwait(continueOnCapturedContext: false);
    }

    private static string VerifyPackageContents(string packagePath)
    {
        using ZipArchive package = ZipFile.OpenRead(packagePath);

        string[] requiredFiles =
        [
            "analyzers/dotnet/cs/NetAgents.Analyzers.dll",
            "analyzers/dotnet/cs/NetAgents.CodeFixes.dll",
            "buildTransitive/NetAgents.Analyzers.props",
            "buildTransitive/NetAgents.Analyzers.targets",
            "buildTransitive/NetAgents.globalconfig",
            "README.md",
            "LICENSE",
        ];

        foreach (string requiredFile in requiredFiles)
            Assert.NotNull(package.GetEntry(requiredFile));

        Assert.Equal(
            expected: 2,
            package.Entries.Count(
                static entry => entry.FullName.StartsWith(value: "analyzers/", StringComparison.Ordinal)
            && entry.FullName.EndsWith(value: ".dll", StringComparison.Ordinal)
            )
        );
        Assert.NotNull(package.GetEntry(entryName: "tools/net10.0/NetAgents.BuildTasks.dll"));
        Assert.NotNull(package.GetEntry(entryName: "tools/net10.0/Microsoft.CodeAnalysis.Workspaces.dll"));

        ZipArchiveEntry manifestEntry = package.GetEntry(entryName: "NetAgents.Analyzers.nuspec")
            ?? throw new InvalidOperationException(message: "The package manifest is missing.");

        using Stream manifestStream = manifestEntry.Open();

        XDocument manifest = XDocument.Load(manifestStream);
        Assert.DoesNotContain(manifest.Descendants(), static element => element.Name.LocalName == "dependency");

        return manifest.Descendants().Single(static element => element.Name.LocalName == "version").Value;
    }
}
