using NetAgents.Analyzers.Concurrency;
using NetAgents.Analyzers.Exceptions;
using NetAgents.Analyzers.Naming;
using NetAgents.Analyzers.SourceFiles;
using NetAgents.Analyzers.Tests.Infrastructure;
using NetAgents.Analyzers.TypeSafety;

namespace NetAgents.Analyzers.Tests.Policy;

public sealed class SyntaxPolicyAnalyzerTests
{
    [Fact]
    public async Task RejectsLockStatements()
    {
        Microsoft.CodeAnalysis.Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(
            new LockStatementAnalyzer(), source: "public class ExampleType { public void Execute() { lock (this) { } } }");
        _ = Assert.Single(diagnostics);
    }

    [Fact]
    public async Task RejectsCommentOnlyCatchBlocks()
    {
        Microsoft.CodeAnalysis.Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(
            new EmptyCatchBlockAnalyzer(), source: "public class ExampleType { public void Execute() { try { } catch { /* ignored */ } } }");
        _ = Assert.Single(diagnostics);
    }

    [Fact]
    public async Task AllowsRethrowingCaughtExceptions()
    {
        Microsoft.CodeAnalysis.Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(
            new EmptyCatchBlockAnalyzer(), source: "public class ExampleType { public void Execute() { try { } catch { throw; } } }");
        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task RejectsNullForgivingOperators()
    {
        Microsoft.CodeAnalysis.Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(
            new NullForgivingOperatorAnalyzer(), source: "public class ExampleType { public string Value => null!; }");
        _ = Assert.Single(diagnostics);
    }

    [Theory]
    [InlineData("while (true) { break; }")]
    [InlineData("for (;;) { break; }")]
    [InlineData("do { break; } while (true);")]
    public async Task RejectsUnconditionalLoops(string loop)
    {
        Microsoft.CodeAnalysis.Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(
            new UnconditionalLoopAnalyzer(), $"public class ExampleType {{ public void Execute() {{ {loop} }} }}");
        _ = Assert.Single(diagnostics);
    }

    [Fact]
    public async Task AllowsCancellationControlledLoops()
    {
        Microsoft.CodeAnalysis.Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(
            new UnconditionalLoopAnalyzer(), source: "public class ExampleType { public void Execute(System.Threading.CancellationToken cancellationToken) { while (!cancellationToken.IsCancellationRequested) { } } }");
        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task RejectsOversizedSourceFiles()
    {
        string source = "public class ExampleType { }" + new string(c: '\n', count: 999);
        Microsoft.CodeAnalysis.Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(new SourceFileLengthAnalyzer(), source);
        _ = Assert.Single(diagnostics);
    }

    [Fact]
    public async Task RejectsNamespaceContainmentCollisions()
    {
        Microsoft.CodeAnalysis.Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(
            new TypeContainmentNameAnalyzer(), source: "namespace ExampleType { public class ExampleType { } }");
        _ = Assert.Single(diagnostics);
    }

    [Fact]
    public async Task ExcludesGeneratedSource()
    {
        Microsoft.CodeAnalysis.Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(
            new LockStatementAnalyzer(), source: "// <auto-generated/>\npublic class ExampleType { public void Execute() { lock (this) { } } }", fileName: "ExampleType.g.cs");
        Assert.Empty(diagnostics);
    }
}