using NetAgents.Analyzers.Concurrency;
using NetAgents.Analyzers.Exceptions;
using NetAgents.Analyzers.Naming;
using NetAgents.Analyzers.SourceFiles;
using NetAgents.Analyzers.Tests.Infrastructure;
using NetAgents.Analyzers.TypeSafety;

namespace NetAgents.Analyzers.Tests.Policy;

/// <summary>
/// Covers syntax policies, source limits, and generated code exclusions.
/// </summary>
public sealed class SyntaxPolicyAnalyzerTests
{
    /// <summary>
    /// Verifies that cancellation provides an accepted loop condition.
    /// </summary>
    [Fact]
    public async Task AllowsCancellationControlledLoops()
    {
        Microsoft.CodeAnalysis.Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(
            new UnconditionalLoopAnalyzer(),
            source: "public class ExampleType { public void Execute(System.Threading.CancellationToken cancellationToken) { while (!cancellationToken.IsCancellationRequested) { } } }"
        );

        Assert.Empty(diagnostics);
    }

    /// <summary>
    /// Verifies that rethrowing a caught exception is permitted.
    /// </summary>
    [Fact]
    public async Task AllowsRethrowingCaughtExceptions()
    {
        Microsoft.CodeAnalysis.Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(new EmptyCatchBlockAnalyzer(), source: "public class ExampleType { public void Execute() { try { } catch { throw; } } }");

        Assert.Empty(diagnostics);
    }

    /// <summary>
    /// Verifies that generated source is excluded from custom analysis.
    /// </summary>
    [Fact]
    public async Task ExcludesGeneratedSource()
    {
        Microsoft.CodeAnalysis.Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(
            new LockStatementAnalyzer(),
            source: "// <auto-generated/>\npublic class ExampleType { public void Execute() { lock (this) { } } }",
            fileName: "ExampleType.g.cs"
        );

        Assert.Empty(diagnostics);
    }

    /// <summary>
    /// Verifies that a comment does not make an empty catch block meaningful.
    /// </summary>
    [Fact]
    public async Task RejectsCommentOnlyCatchBlocks()
    {
        Microsoft.CodeAnalysis.Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(new EmptyCatchBlockAnalyzer(), source: "public class ExampleType { public void Execute() { try { } catch { /* ignored */ } } }");

        Assert.Equal(EmptyCatchBlockAnalyzer.RuleIdentifier, Assert.Single(diagnostics).Id);
    }

    /// <summary>
    /// Verifies that lock statements produce a diagnostic.
    /// </summary>
    [Fact]
    public async Task RejectsLockStatements()
    {
        Microsoft.CodeAnalysis.Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(new LockStatementAnalyzer(), source: "public class ExampleType { public void Execute() { lock (this) { } } }");

        Assert.Equal(LockStatementAnalyzer.RuleIdentifier, Assert.Single(diagnostics).Id);
    }

    /// <summary>
    /// Verifies that a type cannot duplicate its containing namespace name.
    /// </summary>
    [Fact]
    public async Task RejectsNamespaceContainmentCollisions()
    {
        Microsoft.CodeAnalysis.Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(new TypeContainmentNameAnalyzer(), source: "namespace ExampleType { public class ExampleType { } }");

        Assert.Equal(TypeContainmentNameAnalyzer.RuleIdentifier, Assert.Single(diagnostics).Id);
    }

    /// <summary>
    /// Verifies that null-forgiving operators produce a diagnostic.
    /// </summary>
    [Fact]
    public async Task RejectsNullForgivingOperators()
    {
        Microsoft.CodeAnalysis.Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(new NullForgivingOperatorAnalyzer(), source: "public class ExampleType { public string Value => null!; }");

        Assert.Equal(NullForgivingOperatorAnalyzer.RuleIdentifier, Assert.Single(diagnostics).Id);
    }

    /// <summary>
    /// Verifies the authored source file length limit.
    /// </summary>
    [Fact]
    public async Task RejectsOversizedSourceFiles()
    {
        string source = "public class ExampleType { }" + new string(c: '\n', count: 999);
        Microsoft.CodeAnalysis.Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(new SourceFileLengthAnalyzer(), source);
        Assert.Equal(SourceFileLengthAnalyzer.RuleIdentifier, Assert.Single(diagnostics).Id);
    }

    /// <summary>
    /// Verifies that loops without a terminating condition are rejected.
    /// </summary>
    /// <param name="loop">The unconditional loop to analyze.</param>
    [Theory]
    [InlineData("while (true) { break; }")]
    [InlineData("for (;;) { break; }")]
    [InlineData("do { break; } while (true);")]
    public async Task RejectsUnconditionalLoops(string loop)
    {
        Microsoft.CodeAnalysis.Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(new UnconditionalLoopAnalyzer(), $"public class ExampleType {{ public void Execute() {{ {loop} }} }}");

        Assert.Equal(UnconditionalLoopAnalyzer.RuleIdentifier, Assert.Single(diagnostics).Id);
    }
}
