using System.Collections.Immutable;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CodeActions;
using Microsoft.CodeAnalysis.CodeFixes;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Formatting;
using Microsoft.CodeAnalysis.Rename;
using Microsoft.CodeAnalysis.Text;

namespace NetAgents.BuildTasks;

internal static class CodeFixRunner
{
    private static readonly string[] GeneratedSuffixes = [".g.cs", ".g.i.cs", ".generated.cs", ".designer.cs"];

    public static async Task<Project> Fix(Project project, ImmutableArray<DiagnosticAnalyzer> analyzers, CodeFixProvider[] providers, CancellationToken cancellationToken)
    {
        ImmutableHashSet<DocumentId> editable = [];

        foreach (Document document in project.Documents)
        {
            SourceText source = await document.GetTextAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            string header = source.ToString(new TextSpan(start: 0, Math.Min(source.Length, val2: 1024)));

            // Both spellings and suffixes match Roslyn's own generated-code detection, so the
            // formatter skips exactly the files the analyzers already refuse to look at.
            bool generated = GeneratedSuffixes.Any(suffix => document.Name.EndsWith(suffix, StringComparison.OrdinalIgnoreCase))
                || header.Contains(value: "<auto-generated", StringComparison.OrdinalIgnoreCase)
                || header.Contains(value: "<autogenerated", StringComparison.OrdinalIgnoreCase);

            if (!generated)
                editable = editable.Add(document.Id);
        }

        HashSet<string> states = [];
        string? attempt = null;

        while (!cancellationToken.IsCancellationRequested)
        {
            cancellationToken.ThrowIfCancellationRequested();
            project = await FormatWhitespace(project, editable, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);

            Compilation compilation = await project.GetCompilationAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false)
                ?? throw new InvalidOperationException(message: "The formatting compilation is unavailable.");

            ImmutableArray<Diagnostic> diagnostics = await compilation.WithAnalyzers(analyzers, project.AnalyzerOptions)
                .GetAllDiagnosticsAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);

            StringBuilder state = new();

            foreach (Document document in project.Documents)
            {
                SourceText text = await document.GetTextAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                state = state.Append(document.Id).Append(value: ':').Append(text.Length).Append(value: ':').Append(text);
            }

            string fingerprint = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(state.ToString())));

            if (!states.Add(fingerprint))
                throw Failure(reason: "repeated a project state without stabilizing", attempt, diagnostics);

            (Project? fixedProject, string? attemptedAction) = await ApplyAvailableFix(project, diagnostics, analyzers, providers, editable, cancellationToken)
                .ConfigureAwait(continueOnCapturedContext: false);
            attempt = attemptedAction;

            if (fixedProject is null)
                return attempt is not null ? throw Failure(reason: "made no progress", attempt, diagnostics) : project;

            project = fixedProject;
        }

        cancellationToken.ThrowIfCancellationRequested();

        throw new InvalidOperationException(message: "The formatting operation ended without completing.");
    }

    private static async Task<(Project? Project, string? Attempt)> ApplyAvailableFix(
        Project project,
        ImmutableArray<Diagnostic> diagnostics,
        ImmutableArray<DiagnosticAnalyzer> analyzers,
        CodeFixProvider[] providers,
        ImmutableHashSet<DocumentId> editable,
        CancellationToken cancellationToken
    )
    {
        string? attempt = null;
        HashSet<string> rejectedFixAllActions = [];
        (Project? collisionProject, string? collisionAttempt) = await AvoidNamingCollisions(project, diagnostics, editable, cancellationToken)
            .ConfigureAwait(continueOnCapturedContext: false);

        if (collisionProject is not null)
        {
            Project renamed = await ReparseChangedDocuments(project, collisionProject, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);

            ImmutableArray<Diagnostic> renameErrors = await GetIntroducedErrors(renamed, diagnostics, analyzers, cancellationToken)
                .ConfigureAwait(continueOnCapturedContext: false);

            ImmutableArray<Diagnostic> renameCompilerErrors = [.. renameErrors.Where(IsCompilerError)];

            return renameCompilerErrors.IsEmpty
                ? (renamed, collisionAttempt)
                : throw Failure(reason: "introduced compiler errors", collisionAttempt, renameCompilerErrors);
        }

        // A total order keeps the chosen fix identical across runs despite parallel analyzer output.
        IOrderedEnumerable<Diagnostic> ordered = diagnostics.ToArray().OrderBy(static diagnostic => diagnostic.Id, StringComparer.Ordinal)
            .ThenBy(static diagnostic => diagnostic.Location.SourceTree?.FilePath ?? string.Empty, StringComparer.Ordinal)
            .ThenBy(static diagnostic => diagnostic.Location.SourceSpan.Start);

        foreach (Diagnostic diagnostic in ordered)
        {
            Document? document = diagnostic.Location.SourceTree is null ? null : project.GetDocument(diagnostic.Location.SourceTree);

            if (document is null || !editable.Contains(document.Id) || diagnostic.IsSuppressed)
                continue;

            foreach (CodeFixProvider provider in providers.Where(provider => provider.FixableDiagnosticIds.Contains(diagnostic.Id)))
            {
                List<CodeAction> actions = [];
                await provider.RegisterCodeFixesAsync(new CodeFixContext(document, diagnostic, (action, associatedDiagnostics) => actions.Add(action), cancellationToken)).ConfigureAwait(continueOnCapturedContext: false);

                foreach (CodeAction action in actions)
                {
                    CodeAction selected = action;

                    while (!selected.NestedActions.IsEmpty)
                        selected = selected.NestedActions[index: 0];

                    FixAllProvider? fixAllProvider = provider.GetFixAllProvider();

                    bool canFixProject = fixAllProvider is not null && selected.EquivalenceKey is not null
                        && fixAllProvider.GetSupportedFixAllScopes().Contains(FixAllScope.Project);

                    string? fixAllKey = canFixProject
                        ? $"{provider.GetType().FullName}|{selected.EquivalenceKey}"
                        : null;

                    if (fixAllKey is not null && rejectedFixAllActions.Contains(fixAllKey))
                        continue;

                    if (canFixProject && fixAllProvider is not null)
                    {
                        FixAllContext context = new(
                            document,
                            provider,
                            FixAllScope.Project,
                            selected.EquivalenceKey,
                            [.. provider.FixableDiagnosticIds],
                            new BuildDiagnostics(diagnostics),
                            cancellationToken
                        );

                        selected = await fixAllProvider.GetFixAsync(context).ConfigureAwait(continueOnCapturedContext: false) ?? selected;
                    }

                    ImmutableArray<CodeActionOperation> operations = await selected.GetOperationsAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                    ApplyChangesOperation? change = operations.OfType<ApplyChangesOperation>().FirstOrDefault();
                    Project? updated = change?.ChangedSolution.GetProject(project.Id);

                    if (updated is null)
                        continue;

                    ProjectChanges differences = updated.GetChanges(project);
                    DocumentId[] changedDocuments = [.. differences.GetChangedDocuments()];

                    bool supported = changedDocuments.All(editable.Contains)
                        && !differences.GetAddedDocuments().Any() && !differences.GetRemovedDocuments().Any();

                    if (!supported)
                        continue;

                    attempt = $"{diagnostic} — code action '{selected.Title}'";

                    // Comparing text first keeps an action that rewrites nothing off the analyzer path.
                    if (!await HasTextChanges(project, updated, changedDocuments, cancellationToken).ConfigureAwait(continueOnCapturedContext: false))
                        continue;

                    updated = await ReparseChangedDocuments(project, updated, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);

                    ImmutableArray<Diagnostic> introducedErrors = await GetIntroducedErrors(updated, diagnostics, analyzers, cancellationToken)
                        .ConfigureAwait(continueOnCapturedContext: false);

                    ImmutableArray<Diagnostic> introducedCompilerErrors = [.. introducedErrors.Where(IsCompilerError)];

                    if (!introducedCompilerErrors.IsEmpty)
                        throw Failure(reason: "introduced compiler errors", attempt, introducedCompilerErrors);

                    // An error already fails the build, so only lower severities must avoid new analyzer errors.
                    if (diagnostic.Severity != DiagnosticSeverity.Error && !introducedErrors.IsEmpty)
                    {
                        if (fixAllKey is not null && !rejectedFixAllActions.Add(fixAllKey))
                            throw new InvalidOperationException(message: "The rejected formatting action was already recorded.");

                        continue;
                    }

                    return (updated, attempt);
                }
            }
        }

        return diagnostics.Any(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            ? (null, attempt)
            : (null, null);
    }

    private static async Task<Project?> AvoidNamingCollision(Document document, TextSpan diagnosticSpan, CancellationToken cancellationToken)
    {
        SyntaxNode root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false)
            ?? throw new InvalidOperationException(message: "The naming document has no syntax root.");

        SemanticModel model = await document.GetSemanticModelAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false)
            ?? throw new InvalidOperationException(message: "The naming document has no semantic model.");

        if (model.GetDeclaredSymbol(root.FindNode(diagnosticSpan), cancellationToken) is not ILocalSymbol local)
            return null;

        // ponytail: handles case-only collisions; extend the comparison if other naming transformations need repair.
        bool collision = model.LookupSymbols(diagnosticSpan.Start).Any(
            symbol =>
            symbol is ILocalSymbol or IParameterSymbol && !SymbolEqualityComparer.Default.Equals(symbol, local)
                && string.Equals(symbol.Name, local.Name, StringComparison.OrdinalIgnoreCase)
        );

        if (!collision)
            return null;

        HashSet<string> identifiers = root.DescendantTokens().Where(static token => token.IsKind(SyntaxKind.IdentifierToken))
            .Select(static token => token.ValueText).ToHashSet(StringComparer.OrdinalIgnoreCase);

        string name = local.Name + "Value";

        while (identifiers.Contains(name))
            name += "Value";

        Solution renamed = await Renamer.RenameSymbolAsync(document.Project.Solution, local, new SymbolRenameOptions(), name, cancellationToken)
            .ConfigureAwait(continueOnCapturedContext: false);

        return renamed.GetProject(document.Project.Id);
    }

    private static async Task<(Project? Project, string? Attempt)> AvoidNamingCollisions(
        Project project,
        ImmutableArray<Diagnostic> diagnostics,
        ImmutableHashSet<DocumentId> editable,
        CancellationToken cancellationToken
    )
    {
        List<(DocumentId Document, TextSpan SourceSpan, Diagnostic Diagnostic)> candidates = [];

        foreach (Diagnostic diagnostic in diagnostics)
        {
            Document? document = diagnostic.Id == "IDE1006" && diagnostic.Location.SourceTree is not null
                ? project.GetDocument(diagnostic.Location.SourceTree)
                : null;

            if (document is not null && editable.Contains(document.Id))
                candidates.Add((document.Id, diagnostic.Location.SourceSpan, diagnostic));
        }

        Project updated = project;
        Diagnostic? first = null;

        foreach (
            (DocumentId Document, TextSpan SourceSpan, Diagnostic Diagnostic) candidate in candidates
                .OrderBy(static candidate => candidate.Document.Id)
                .ThenByDescending(static candidate => candidate.SourceSpan.Start)
        )
        {
            Document document = updated.GetDocument(candidate.Document) ?? throw new InvalidOperationException(message: "The naming document is missing.");
            Project? renamed = await AvoidNamingCollision(document, candidate.SourceSpan, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);

            if (renamed is null)
                continue;

            updated = renamed;
            first ??= candidate.Diagnostic;
        }

        return first is null
            ? (null, null)
            : (updated, $"{first} — rename colliding locals before applying naming-style fixes");
    }

    private static (string Identifier, string Message, string Path) ErrorKey(Diagnostic diagnostic)
    {
        return (diagnostic.Id, diagnostic.GetMessage(CultureInfo.InvariantCulture), diagnostic.Location.SourceTree?.FilePath ?? string.Empty);
    }

    private static InvalidOperationException Failure(string reason, string? attempt, ImmutableArray<Diagnostic> diagnostics)
    {
        // Oscillating analyzer fixes are the usual cause, so every error is listed, not just compiler errors.
        string errors = string.Join(Environment.NewLine, diagnostics.Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));

        return new InvalidOperationException($"Automatic formatting {reason}. Attempted code action: {attempt}{Environment.NewLine}{errors}");
    }

    private static async Task<Project> FormatWhitespace(Project project, ImmutableHashSet<DocumentId> editable, CancellationToken cancellationToken)
    {
        foreach (DocumentId identifier in editable)
        {
            Document document = project.GetDocument(identifier) ?? throw new InvalidOperationException(message: "A formatting document is missing.");
            Document formatted = await Formatter.FormatAsync(document, cancellationToken: cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            SourceText text = await formatted.GetTextAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            SyntaxTree? tree = await formatted.GetSyntaxTreeAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            AnalyzerConfigOptions options = project.AnalyzerOptions.AnalyzerConfigOptionsProvider.GetOptions(tree ?? throw new InvalidOperationException(message: "A syntax tree is missing."));

            bool needsFinalNewline = text.Length > 0 && text.Lines.GetLineFromPosition(text.Length).Span.Length > 0
                && options.TryGetValue(key: "insert_final_newline", out string? finalNewline) && finalNewline == "true";

            if (needsFinalNewline)
                formatted = formatted.WithText(text.WithChanges(new TextChange(new TextSpan(text.Length, length: 0), GetLineEnding(text, options))));

            project = formatted.Project;
        }

        return project;
    }

    private static async Task<ImmutableArray<Diagnostic>> GetIntroducedErrors(
        Project after,
        ImmutableArray<Diagnostic> beforeDiagnostics,
        ImmutableArray<DiagnosticAnalyzer> analyzers,
        CancellationToken cancellationToken
    )
    {
        Compilation compilation = await after.GetCompilationAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false)
            ?? throw new InvalidOperationException(message: "The formatting compilation is unavailable.");

        ImmutableArray<Diagnostic> afterDiagnostics = await compilation.WithAnalyzers(analyzers, after.AnalyzerOptions)
            .GetAllDiagnosticsAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);

        Dictionary<(string Identifier, string Message, string Path), int> existingErrors = beforeDiagnostics
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .CountBy(ErrorKey).ToDictionary();

        return [.. afterDiagnostics
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .GroupBy(ErrorKey)
            .SelectMany(group => group.Skip(existingErrors.GetValueOrDefault(group.Key)))];
    }

    private static string GetLineEnding(SourceText text, AnalyzerConfigOptions options)
    {
        if (options.TryGetValue(key: "end_of_line", out string? configured))
            return configured switch { "crlf" => "\r\n", "cr" => "\r", _ => "\n" };

        // Without a configured value, appending anything else would mix endings within one file.
        foreach (TextLine line in text.Lines)
        {
            if (line.EndIncludingLineBreak > line.End)
                return text.ToString(TextSpan.FromBounds(line.End, line.EndIncludingLineBreak));
        }

        return "\n";
    }

    private static async Task<bool> HasTextChanges(Project before, Project after, DocumentId[] changedDocuments, CancellationToken cancellationToken)
    {
        foreach (DocumentId identifier in changedDocuments)
        {
            Document beforeDocument = before.GetDocument(identifier) ?? throw new InvalidOperationException(message: "The original document is missing.");
            Document afterDocument = after.GetDocument(identifier) ?? throw new InvalidOperationException(message: "The updated document is missing.");
            SourceText beforeText = await beforeDocument.GetTextAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            SourceText afterText = await afterDocument.GetTextAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);

            if (!beforeText.ContentEquals(afterText))
                return true;
        }

        return false;
    }

    private static bool IsCompilerError(Diagnostic diagnostic)
    {
        return diagnostic.Id.StartsWith(value: "CS", StringComparison.Ordinal);
    }

    private static async Task<Project> ReparseChangedDocuments(Project before, Project after, CancellationToken cancellationToken)
    {
        foreach (DocumentId identifier in after.GetChanges(before).GetChangedDocuments())
        {
            Document document = after.GetDocument(identifier) ?? throw new InvalidOperationException(message: "The updated document is missing.");
            SourceText text = await document.GetTextAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            after = document.WithText(SourceText.From(text.ToString(), text.Encoding, text.ChecksumAlgorithm)).Project;
        }

        return after;
    }
}
