using System.Collections.Immutable;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CodeActions;
using Microsoft.CodeAnalysis.CodeFixes;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Formatting;
using Microsoft.CodeAnalysis.Text;

namespace NetAgents.BuildTasks;

internal static class CodeFixRunner
{
    public static async Task<Project> Fix(Project project, ImmutableArray<DiagnosticAnalyzer> analyzers, CodeFixProvider[] providers, CancellationToken cancellationToken)
    {
        ImmutableHashSet<DocumentId> editable = [];

        foreach (Document document in project.Documents)
        {
            SourceText source = await document.GetTextAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            string header = source.ToString(new TextSpan(start: 0, Math.Min(source.Length, val2: 1024)));

            bool generated = document.Name.EndsWith(value: ".g.cs", StringComparison.OrdinalIgnoreCase)
                || document.Name.EndsWith(value: ".generated.cs", StringComparison.OrdinalIgnoreCase)
                || header.Contains(value: "<auto-generated", StringComparison.OrdinalIgnoreCase);

            if (!generated)
                editable = editable.Add(document.Id);
        }

        for (int pass = 0; pass < 64; pass++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            project = await FormatWhitespace(project, editable, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);

            Compilation compilation = await project.GetCompilationAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false)
                ?? throw new InvalidOperationException(message: "The formatting compilation is unavailable.");

            ImmutableArray<Diagnostic> diagnostics = await compilation.WithAnalyzers(analyzers, project.AnalyzerOptions)
                .GetAllDiagnosticsAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);

            Project? fixedProject = await ApplyAvailableFix(project, diagnostics, providers, editable, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);

            if (fixedProject is null)
                return project;

            project = fixedProject;
        }

        throw new InvalidOperationException(message: "Automatic formatting did not stabilize after 64 fix passes. Resolve conflicting code fixes before rebuilding.");
    }

    private static async Task<Project> FormatWhitespace(Project project, ImmutableHashSet<DocumentId> editable, CancellationToken cancellationToken)
    {
        foreach (DocumentId identifier in editable)
        {
            Document document = project.GetDocument(identifier) ?? throw new InvalidOperationException(message: "A formatting document is missing.");
            Document formatted = await Formatter.FormatAsync(document, cancellationToken: cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            SourceText text = await formatted.GetTextAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            SyntaxTree? tree = await formatted.GetSyntaxTreeAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            AnalyzerConfigOptions options = project.AnalyzerOptions.AnalyzerConfigOptionsProvider.GetOptions(tree ?? throw new InvalidOperationException(message: "A syntax tree is missing."));

            bool needsFinalNewline = text.Length > 0 && text.Lines.GetLineFromPosition(text.Length).Span.Length > 0
                && options.TryGetValue(key: "insert_final_newline", out string? finalNewline) && finalNewline == "true";

            if (needsFinalNewline)
            {
                string newline = options.TryGetValue(key: "end_of_line", out string? lineEnding) && lineEnding == "crlf" ? "\r\n" : "\n";
                formatted = formatted.WithText(text.WithChanges(new TextChange(new TextSpan(text.Length, length: 0), newline)));
            }

            project = formatted.Project;
        }

        return project;
    }

    private static async Task<Project?> ApplyAvailableFix(
        Project project,
        ImmutableArray<Diagnostic> diagnostics,
        CodeFixProvider[] providers,
        ImmutableHashSet<DocumentId> editable,
        CancellationToken cancellationToken
    )
    {
        foreach (Diagnostic diagnostic in diagnostics.ToArray().OrderBy(static diagnostic => diagnostic.Id, StringComparer.Ordinal))
        {
            Document? document = diagnostic.Location.SourceTree is null ? null : project.GetDocument(diagnostic.Location.SourceTree);

            bool canFix = document is not null && editable.Contains(document.Id)
                && !diagnostic.IsSuppressed;

            if (!canFix || document is null)
                continue;

            foreach (CodeFixProvider provider in providers.Where(provider => provider.FixableDiagnosticIds.Contains(diagnostic.Id)))
            {
                List<CodeAction> actions = [];
                await provider.RegisterCodeFixesAsync(new CodeFixContext(document, diagnostic, (action, associatedDiagnostics) => actions.Add(action), cancellationToken)).ConfigureAwait(continueOnCapturedContext: false);

                foreach (CodeAction action in actions)
                {
                    CodeAction selected = action;

                    while (!selected.NestedActions.IsEmpty)
                        selected = selected.NestedActions[index: 0];

                    FixAllProvider? fixAllProvider = provider.GetFixAllProvider();

                    bool canFixProject = fixAllProvider is not null && selected.EquivalenceKey is not null
                        && fixAllProvider.GetSupportedFixAllScopes().Contains(FixAllScope.Project);

                    if (canFixProject && fixAllProvider is not null)
                    {
                        FixAllContext context = new(
                            document,
                            provider,
                            FixAllScope.Project,
                            selected.EquivalenceKey,
                            [.. provider.FixableDiagnosticIds],
                            new BuildDiagnostics(diagnostics),
                            cancellationToken
                        );

                        selected = await fixAllProvider.GetFixAsync(context).ConfigureAwait(continueOnCapturedContext: false) ?? selected;
                    }

                    ImmutableArray<CodeActionOperation> operations = await selected.GetOperationsAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                    ApplyChangesOperation? change = operations.OfType<ApplyChangesOperation>().FirstOrDefault();
                    Project? updated = change?.ChangedSolution.GetProject(project.Id);

                    if (updated is null)
                        continue;

                    ProjectChanges differences = updated.GetChanges(project);
                    DocumentId[] changedDocuments = [.. differences.GetChangedDocuments()];

                    bool supported = changedDocuments.All(editable.Contains)
                        && !differences.GetAddedDocuments().Any() && !differences.GetRemovedDocuments().Any();

                    if (!supported)
                        continue;

                    foreach (DocumentId identifier in changedDocuments)
                    {
                        Document beforeDocument = project.GetDocument(identifier) ?? throw new InvalidOperationException(message: "The original document is missing.");
                        Document afterDocument = updated.GetDocument(identifier) ?? throw new InvalidOperationException(message: "The updated document is missing.");
                        SourceText before = await beforeDocument.GetTextAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                        SourceText after = await afterDocument.GetTextAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);

                        if (!before.ContentEquals(after))
                            return updated;
                    }
                }
            }
        }

        return null;
    }
}
