<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <AnalysisMode>All</AnalysisMode>
    <AnalysisLevelStyle>latest-all</AnalysisLevelStyle>
    <AnalysisModeStyle>AllEnabledByDefault</AnalysisModeStyle>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <EnableCodeStyleSeverity>true</EnableCodeStyleSeverity>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RunAnalyzers>true</RunAnalyzers>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1591</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <CompilerVisibleProperty Include="MSBuildProjectDirectory" />
  </ItemGroup>
</Project>
