using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

using NetAgents.Analyzers.CodeFixes.Formatting;
using NetAgents.Analyzers.CodeFixes.Ordering;
using NetAgents.Analyzers.Formatting;
using NetAgents.Analyzers.Ordering;
using NetAgents.Analyzers.Tests.Infrastructure;
using NetAgents.BuildTasks;

namespace NetAgents.Analyzers.Tests.Formatting;

/// <summary>
/// Verifies removal of blank lines at block edges and preservation of surrounding source.
/// </summary>
public sealed class BlockPaddingTests
{
    /// <summary>
    /// Verifies unpadded blocks, literal content, and directive boundaries are left alone.
    /// </summary>
    [Theory]
    [InlineData("class ExampleType { }")]
    [InlineData("class ExampleType\n{\n    void Execute()\n    {\n    }\n}")]
    [InlineData("class ExampleType\n{\n    void First() { }\n\n    void Second() { }\n}")]
    [InlineData("class ExampleType\n{\n    /* text\n\n       text */\n    void Execute() { }\n}")]
    [InlineData("class ExampleType\n{\n    string Text => \"\"\"\n        first\n\n        last\n        \"\"\";\n}")]
    [InlineData("class ExampleType\n{\n#region Members\n\n    void Execute() { }\n\n#endregion\n}")]
    [InlineData("// <auto-generated/>\nclass ExampleType\n{\n\n    void Execute() { }\n}")]
    public async Task AcceptsUnpaddedBlocks(string source)
    {
        Assert.Empty(await AnalyzerTestHarness.Analyze(new BlockPaddingAnalyzer(), source));
    }

    /// <summary>
    /// Verifies edge removal, method spacing, and member ordering reach a fixed point together.
    /// </summary>
    [Fact]
    public async Task ConvergesWithSpacingRules()
    {
        const string source = "class ExampleType\n{\n\n    void Zebra() { }\n    void Alpha() { }\n\n}\n";

        using AdhocWorkspace workspace = new();

        Project project = workspace.AddProject(name: "Convergence", LanguageNames.CSharp)
            .WithCompilationOptions(new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .AddMetadataReferences(AnalyzerTestHarness.References)
            .AddDocument(name: "ExampleType.cs", SourceText.From(source)).Project;

        Project result = await CodeFixRunner.Fix(
            project,
            [new BlockPaddingAnalyzer(), new MethodSpacingAnalyzer(), new MemberOrderingAnalyzer()],
            [new BlockPaddingCodeFixProvider(), new MethodSpacingCodeFixProvider(), new MemberOrderingCodeFixProvider()],
            CancellationToken.None
        );

        string formatted = (await result.Documents.Single().GetTextAsync()).ToString();

        Assert.Equal(expected: "class ExampleType\n{\n    void Alpha() { }\n\n    void Zebra() { }\n}\n", formatted);
        Assert.Empty(await AnalyzerTestHarness.Analyze(new BlockPaddingAnalyzer(), formatted));
        Assert.Empty(await AnalyzerTestHarness.Analyze(new MethodSpacingAnalyzer(), formatted));
        Assert.Empty(await AnalyzerTestHarness.Analyze(new MemberOrderingAnalyzer(), formatted));
    }

    /// <summary>
    /// Verifies every block kind loses padding and keeps its line endings.
    /// </summary>
    [Theory]
    [InlineData("class ExampleType\n{\n\n    void Execute() { }\n}", "class ExampleType\n{\n    void Execute() { }\n}")]
    [InlineData("class ExampleType\n{\n    void Execute() { }\n\n}", "class ExampleType\n{\n    void Execute() { }\n}")]
    [InlineData("class ExampleType\r\n{\r\n\r\n    void Execute() { }\r\n}", "class ExampleType\r\n{\r\n    void Execute() { }\r\n}")]
    [InlineData(
        "class ExampleType\n{\n    void Execute()\n    {\n\n        System.Console.WriteLine();\n    }\n}",
        "class ExampleType\n{\n    void Execute()\n    {\n        System.Console.WriteLine();\n    }\n}"
    )]
    [InlineData(
        "class ExampleType\n{\n    void Execute(bool flag)\n    {\n        if (flag)\n        {\n\n            System.Console.WriteLine();\n        }\n    }\n}",
        "class ExampleType\n{\n    void Execute(bool flag)\n    {\n        if (flag)\n        {\n            System.Console.WriteLine();\n        }\n    }\n}"
    )]
    [InlineData(
        "class ExampleType\n{\n    int Count\n    {\n\n        get => 1;\n    }\n}",
        "class ExampleType\n{\n    int Count\n    {\n        get => 1;\n    }\n}"
    )]
    [InlineData("namespace Example\n{\n\n    class ExampleType { }\n}", "namespace Example\n{\n    class ExampleType { }\n}")]
    [InlineData("enum ExampleKind\n{\n\n    First\n}", "enum ExampleKind\n{\n    First\n}")]
    [InlineData(
        "class ExampleType\n{\n    void Execute(int value)\n    {\n        switch (value)\n        {\n\n            default: break;\n        }\n    }\n}",
        "class ExampleType\n{\n    void Execute(int value)\n    {\n        switch (value)\n        {\n            default: break;\n        }\n    }\n}"
    )]
    [InlineData(
        "class ExampleType\n{\n    int Count;\n\n    ExampleType Create() => new ExampleType\n    {\n\n        Count = 1\n    };\n}",
        "class ExampleType\n{\n    int Count;\n\n    ExampleType Create() => new ExampleType\n    {\n        Count = 1\n    };\n}"
    )]
    [InlineData(
        "class ExampleType\n{\n    System.Action Create() => () =>\n    {\n\n        System.Console.WriteLine();\n    };\n}",
        "class ExampleType\n{\n    System.Action Create() => () =>\n    {\n        System.Console.WriteLine();\n    };\n}"
    )]
    [InlineData(
        "class ExampleType\n{\n    void Execute()\n    {\n        void Local()\n        {\n\n            System.Console.WriteLine();\n        }\n\n        Local();\n    }\n}",
        "class ExampleType\n{\n    void Execute()\n    {\n        void Local()\n        {\n            System.Console.WriteLine();\n        }\n\n        Local();\n    }\n}"
    )]
    [InlineData(
        "class ExampleType\n{\n\n    // Leading comment.\n    void Execute() { }\n}",
        "class ExampleType\n{\n    // Leading comment.\n    void Execute() { }\n}"
    )]
    public async Task FixesPaddedEdges(string source, string expected)
    {
        Assert.Equal(expected, await CodeFixTestHarness.FixBlockPadding(source, fixAll: false));
    }

    /// <summary>
    /// Verifies several padded edges and consecutive blank lines converge in one pass.
    /// </summary>
    [Fact]
    public async Task RemovesEveryPaddedEdge()
    {
        const string source = "class ExampleType\n{\n\n\n    void Execute()\n    {\n\n        System.Console.WriteLine();\n\n    }\n\n}";
        const string expected = "class ExampleType\n{\n    void Execute()\n    {\n        System.Console.WriteLine();\n    }\n}";

        string fixedSource = await CodeFixTestHarness.FixBlockPadding(source, fixAll: true);

        Assert.Equal(expected, fixedSource);
        Assert.Empty(await AnalyzerTestHarness.Analyze(new BlockPaddingAnalyzer(), fixedSource));
    }

    /// <summary>
    /// Verifies an empty block reports a single diagnostic for both of its edges.
    /// </summary>
    [Fact]
    public async Task ReportsEmptyBlockOnce()
    {
        const string source = "class ExampleType\n{\n\n}";

        Diagnostic diagnostic = Assert.Single(await AnalyzerTestHarness.Analyze(new BlockPaddingAnalyzer(), source));

        Assert.Equal(BlockPaddingAnalyzer.RuleIdentifier, diagnostic.Id);
        Assert.Equal(expected: "class ExampleType\n{\n}", await CodeFixTestHarness.FixBlockPadding(source, fixAll: true));
    }
}
