using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CodeActions;
using Microsoft.CodeAnalysis.CodeFixes;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

using NetAgents.Analyzers.Formatting;
using NetAgents.Analyzers.Tests.Infrastructure;
using NetAgents.BuildTasks;

namespace NetAgents.Analyzers.Tests.Formatting;

/// <summary>Checks formatter progress with unresolved compiler diagnostics.</summary>
public sealed class CodeFixRunnerTests
{
    /// <summary>Appends the final newline the document already uses instead of a bare line feed.</summary>
    [Fact]
    public async Task AppendsMatchingFinalNewline()
    {
        using AdhocWorkspace workspace = new();

        Project project = workspace.AddProject(name: "Endings", LanguageNames.CSharp)
            .WithCompilationOptions(new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .AddMetadataReferences(AnalyzerTestHarness.References)
            .AddDocument(name: "Example.cs", SourceText.From(text: "class Example\r\n{\r\n}"), filePath: "/Example.cs").Project
            .AddAnalyzerConfigDocument(name: ".globalconfig", SourceText.From(text: "is_global = true\ninsert_final_newline = true\n"), filePath: "/.globalconfig").Project;

        Project result = await CodeFixRunner.Fix(project, [], [], CancellationToken.None);
        SourceText text = await result.Documents.Single().GetTextAsync();

        Assert.EndsWith(expectedEndString: "}\r\n", text.ToString(), StringComparison.Ordinal);
    }

    /// <summary>Leaves the compiler error in place when its only provider cannot run.</summary>
    /// <param name="stage">The provider stage that fails.</param>
    [Theory]
    [InlineData("identifiers")]
    [InlineData("registration")]
    [InlineData("operations")]
    public async Task PreservesErrorWhenEveryProviderFails(string stage)
    {
        using AdhocWorkspace workspace = new();

        ThrowingFix provider = new(stage);
        Project result = await CodeFixRunner.Fix(CreateProject(workspace), [], [provider], CancellationToken.None);
        Compilation? compilation = await result.GetCompilationAsync();

        Assert.NotNull(compilation);
        Diagnostic error = Assert.Single(compilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
        Assert.Equal(expected: "CS0122", error.Id);

        // The skipped accessibility repair would have replaced this modifier.
        Assert.Contains(
            expectedSubstring: "private static int Value",
            (await result.Documents.Single().GetTextAsync()).ToString(),
            StringComparison.Ordinal
        );
    }

    /// <summary>Applies the single-document action when project-wide fixing cannot run.</summary>
    /// <param name="stage">The project-wide stage that fails.</param>
    [Theory]
    [InlineData("scopes")]
    [InlineData("fixAll")]
    public async Task PreservesFixWhenProjectWideFixingFails(string stage)
    {
        using AdhocWorkspace workspace = new();

        ThrowingFix provider = new(stage);
        Project result = await CodeFixRunner.Fix(CreateProject(workspace), [new MethodSpacingAnalyzer()], [provider], CancellationToken.None);
        Compilation? compilation = await result.GetCompilationAsync();

        Assert.NotNull(compilation);
        Assert.DoesNotContain(compilation.GetDiagnostics().ToArray(), static diagnostic => diagnostic.Id == "CS0122");
        Assert.InRange(provider.Attempts, low: 1, high: 3);
    }

    /// <summary>Leaves generated documents untouched, including the unhyphenated header the SDK emits.</summary>
    /// <param name="header">The generated-code marker introducing the document.</param>
    [Theory]
    [InlineData("// <autogenerated />")]
    [InlineData("// <auto-generated />")]
    public async Task PreservesGeneratedDocuments(string header)
    {
        using AdhocWorkspace workspace = new();

        string generated = header + "\nclass Generated{   void Run( ) { } }\n";

        Project project = CreateProject(workspace)
            .AddDocument(name: "Generated.cs", SourceText.From(generated), filePath: "Generated.cs").Project;

        Project result = await CodeFixRunner.Fix(project, [], [], CancellationToken.None);
        Document document = result.Documents.Single(static candidate => candidate.Name == "Generated.cs");

        Assert.Equal(generated, (await document.GetTextAsync()).ToString());
    }

    /// <summary>Allows existing compiler errors to move when a fix changes preceding text.</summary>
    [Fact]
    public async Task PreservesMovedCompilerError()
    {
        using AdhocWorkspace workspace = new();

        Project project = CreateProject(workspace);
        project = project.Documents.Single().WithText(SourceText.From(text: "class Example { void Run() { int marker = 0; Missing(); } }")).Project;
        ReplacementFix provider = new(source: "class Example { void Run() { Missing(); } }");

        Project result = await CodeFixRunner.Fix(project, [], [provider], CancellationToken.None);
        Compilation? compilation = await result.GetCompilationAsync();

        Assert.NotNull(compilation);
        Diagnostic error = Assert.Single(compilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
        Assert.Equal(expected: "CS0103", error.Id);
        Assert.Equal(expected: 1, provider.Attempts);
    }

    /// <summary>Never offers an unresolved symbol to a code-fix provider, leaving the compiler to report it.</summary>
    /// <param name="body">The statement that leaves a symbol unresolved.</param>
    /// <param name="diagnosticIdentifier">The compiler error the statement produces.</param>
    [Theory]
    [InlineData("Missing();", "CS0103")]
    [InlineData("Sample sample = new();", "CS0246")]
    public async Task PreservesUnresolvedSymbolErrors(string body, string diagnosticIdentifier)
    {
        using AdhocWorkspace workspace = new();

        Project project = CreateProject(workspace);
        string source = $"class Example {{ void Run() {{ {body} }} }}";
        project = project.Documents.Single().WithText(SourceText.From(source)).Project;
        UnresolvedFix provider = new(diagnosticIdentifier);

        Project result = await CodeFixRunner.Fix(project, [], [provider], CancellationToken.None);
        Compilation? compilation = await result.GetCompilationAsync();

        Assert.NotNull(compilation);
        Diagnostic error = Assert.Single(compilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
        Assert.Equal(diagnosticIdentifier, error.Id);
        Assert.Equal(expected: 0, provider.Attempts);
        Assert.Contains(body, (await result.Documents.Single().GetTextAsync()).ToString(), StringComparison.Ordinal);
    }

    /// <summary>Still applies valid automatic fixes to compiler errors.</summary>
    [Theory]
    [InlineData("valid")]
    [InlineData("noop")]
    public async Task PreservesValidCompilerFix(string firstAction)
    {
        using AdhocWorkspace workspace = new();

        CompilerFix provider = new(mode: "valid");
        CodeFixProvider[] providers = firstAction == "noop" ? [new CompilerFix(mode: "noop"), provider] : [provider];
        Project result = await CodeFixRunner.Fix(CreateProject(workspace), [new MethodSpacingAnalyzer()], providers, CancellationToken.None);
        Compilation? compilation = await result.GetCompilationAsync();
        Assert.NotNull(compilation);
        Assert.DoesNotContain(compilation.GetDiagnostics().ToArray(), static diagnostic => diagnostic.Id == "CS0122");
        Assert.Equal(expected: 1, provider.Attempts);
    }

    /// <summary>Rejects new compiler errors before accepting an automatic fix.</summary>
    [Theory]
    [InlineData("", "0 = 1;", "CS0131")]
    [InlineData("Missing();", "0 = 1;", "CS0131")]
    [InlineData("Missing();", "Missing(); Missing();", "CS0103")]
    public async Task RejectsCompilerBreakingFix(string before, string after, string diagnosticIdentifier)
    {
        using AdhocWorkspace workspace = new();

        Project project = CreateProject(workspace);
        Document document = project.Documents.Single();
        string source = $"class Example {{ void Run() {{ int marker = 0; {before} }} }}";
        project = document.WithText(SourceText.From(source)).Project;
        ReplacementFix provider = new($"class Example {{ void Run() {{ {after} }} }}");

        InvalidOperationException exception = await Assert.ThrowsAsync<InvalidOperationException>(() => CodeFixRunner.Fix(project, [], [provider], CancellationToken.None));

        Assert.Contains(expectedSubstring: "introduced compiler errors", exception.Message, StringComparison.Ordinal);
        Assert.Contains(expectedSubstring: "Replace method body", exception.Message, StringComparison.Ordinal);
        Assert.Contains(diagnosticIdentifier, exception.Message, StringComparison.Ordinal);
        Assert.Equal(expected: 1, provider.Attempts);
        Assert.Equal(source, (await project.Documents.Single().GetTextAsync()).ToString());
    }

    /// <summary>Reports stalled actions without exhausting the pass limit.</summary>
    [Theory]
    [InlineData("noop")]
    [InlineData("whitespace")]
    [InlineData("cycle")]
    public async Task ReportsStalledCompilerFix(string mode)
    {
        using AdhocWorkspace workspace = new();

        Project project = CreateProject(workspace);
        CompilerFix provider = new(mode);

        InvalidOperationException exception = await Assert.ThrowsAsync<InvalidOperationException>(() => CodeFixRunner.Fix(project, [new MethodSpacingAnalyzer()], [provider], CancellationToken.None));

        Assert.Contains(expectedSubstring: "CS0122", exception.Message, StringComparison.Ordinal);
        Assert.Matches(expectedRegexPattern: @"Example\.cs\([1-9][0-9]*,[1-9][0-9]*\): error CS0122", exception.Message);
        Assert.Contains(expectedSubstring: "Attempt accessibility repair", exception.Message, StringComparison.Ordinal);
        Assert.DoesNotContain(expectedSubstring: "fix passes", exception.Message, StringComparison.Ordinal);
        Assert.InRange(provider.Attempts, low: 1, high: 3);
    }

    /// <summary>Drops a suggestion's compiler-breaking action instead of failing an otherwise clean build.</summary>
    [Fact]
    public async Task SkipsCompilerBreakingSuggestionFix()
    {
        using AdhocWorkspace workspace = new();

        // CS8019 is a hidden compiler suggestion, so nothing about this document has to be repaired.
        Project project = CreateProject(workspace);
        const string source = "using System;\nclass Example { int Read() => 0; }";
        project = project.Documents.Single().WithText(SourceText.From(source)).Project;
        SuggestionFix provider = new(source: "using System;\nclass Example { int Read() => \"text\"; }");

        Project result = await CodeFixRunner.Fix(project, [], [provider], CancellationToken.None);

        Assert.Equal(source, (await result.Documents.Single().GetTextAsync()).ToString());
        Assert.InRange(provider.Attempts, low: 1, high: 2);
    }

    /// <summary>Skips a failing provider while another provider still repairs the compiler error.</summary>
    /// <param name="stage">The provider stage that fails.</param>
    [Theory]
    [InlineData("identifiers")]
    [InlineData("registration")]
    [InlineData("operations")]
    public async Task SkipsFailingCodeFixProvider(string stage)
    {
        using AdhocWorkspace workspace = new();

        ThrowingFix throwing = new(stage);
        CompilerFix working = new(mode: "valid");
        int expectedAttempts = stage == "identifiers" ? 0 : 1;
        Project result = await CodeFixRunner.Fix(CreateProject(workspace), [new MethodSpacingAnalyzer()], [throwing, working], CancellationToken.None);
        Compilation? compilation = await result.GetCompilationAsync();

        Assert.NotNull(compilation);
        Assert.DoesNotContain(compilation.GetDiagnostics().ToArray(), static diagnostic => diagnostic.Id == "CS0122");
        Assert.Equal(expected: 1, working.Attempts);
        Assert.Equal(expectedAttempts, throwing.Attempts);
    }

    private static Project CreateProject(AdhocWorkspace workspace)
    {
        return workspace.AddProject(name: "Progress", LanguageNames.CSharp)
            .WithCompilationOptions(new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .AddMetadataReferences(AnalyzerTestHarness.References)
            .AddDocument(
                name: "Example.cs",
                SourceText.From(text: "class Hidden { private static int Value; } class Consumer { int Read() => Hidden.Value; }"),
                filePath: "Example.cs"
            ).Project;
    }

    private sealed class CompilerFix(string mode) : CodeFixProvider
    {
        public int Attempts { get; private set; }

        public override ImmutableArray<string> FixableDiagnosticIds => ["CS0122"];

        public override Task RegisterCodeFixesAsync(CodeFixContext context)
        {
            Attempts++;
            context.RegisterCodeFix(
                CodeAction.Create(
                    title: "Attempt accessibility repair",
                    async cancellationToken =>
            {
                SourceText text = await context.Document.GetTextAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                string source = text.ToString();

                string changed = mode switch
                {
                    "valid" => source.Replace(oldValue: "private", newValue: "public", StringComparison.Ordinal),
                    "whitespace" => source.Replace(oldValue: "class Hidden", newValue: "class  Hidden", StringComparison.Ordinal),
                    "cycle" => source.Contains(value: "class Consumer", StringComparison.Ordinal)
                        ? source.Replace(oldValue: "class Consumer", newValue: "class Alternate", StringComparison.Ordinal)
                        : source.Replace(oldValue: "class Alternate", newValue: "class Consumer", StringComparison.Ordinal),
                    _ => source,
                };

                return context.Document.WithText(SourceText.From(changed));
            }
                ),
                context.Diagnostics
            );

            return Task.CompletedTask;
        }
    }

    private sealed class ReplacementFix(string source) : CodeFixProvider
    {
        public int Attempts { get; private set; }

        public override ImmutableArray<string> FixableDiagnosticIds => ["CS0219"];

        public override Task RegisterCodeFixesAsync(CodeFixContext context)
        {
            Attempts++;
            context.RegisterCodeFix(
                CodeAction.Create(title: "Replace method body", cancellationToken => Task.FromResult(context.Document.WithText(SourceText.From(source)))),
                context.Diagnostics
            );

            return Task.CompletedTask;
        }
    }

    /// <summary>Offers a suggestion fix that replaces the document with uncompilable source.</summary>
    private sealed class SuggestionFix(string source) : CodeFixProvider
    {
        public int Attempts { get; private set; }

        public override ImmutableArray<string> FixableDiagnosticIds => ["CS8019"];

        public override Task RegisterCodeFixesAsync(CodeFixContext context)
        {
            Attempts++;
            context.RegisterCodeFix(
                CodeAction.Create(title: "Replace suggestion body", cancellationToken => Task.FromResult(context.Document.WithText(SourceText.From(source)))),
                context.Diagnostics
            );

            return Task.CompletedTask;
        }
    }

    /// <summary>Reproduces a provider built against another Roslyn version, failing at one chosen stage.</summary>
    private sealed class ThrowingFix(string stage) : CodeFixProvider
    {
        public int Attempts { get; private set; }

        [SuppressMessage("Design", "CA1065", Justification = "A skewed provider fails exactly here, which is the behavior under test.")]
        public override ImmutableArray<string> FixableDiagnosticIds => stage == "identifiers" ? throw Skew() : ["CS0122"];

        public override FixAllProvider? GetFixAllProvider()
        {
            return stage switch
            {
                "scopes" => new ThrowingFixAll(failOnScopes: true),
                "fixAll" => new ThrowingFixAll(failOnScopes: false),
                _ => null,
            };
        }

        public override Task RegisterCodeFixesAsync(CodeFixContext context)
        {
            Attempts++;

            if (stage == "registration")
                throw Skew();

            context.RegisterCodeFix(
                CodeAction.Create(
                    title: "Repair accessibility",
                    async cancellationToken =>
            {
                if (stage == "operations")
                    throw Skew();

                SourceText text = await context.Document.GetTextAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                string changed = text.ToString().Replace(oldValue: "private", newValue: "public", StringComparison.Ordinal);

                return context.Document.WithText(SourceText.From(changed));
            },
                    equivalenceKey: "NetAgentsThrowingFix"
                ),
                context.Diagnostics
            );

            return Task.CompletedTask;
        }

        private static MissingMethodException Skew()
        {
            return new MissingMethodException(message: "Method not found: 'Void Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationContext..ctor()'.");
        }
    }

    private sealed class ThrowingFixAll(bool failOnScopes) : FixAllProvider
    {
        public override Task<CodeAction?> GetFixAsync(FixAllContext fixAllContext)
        {
            throw new MissingMethodException(message: "Method not found: 'Void Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationContext..ctor()'.");
        }

        public override IEnumerable<FixAllScope> GetSupportedFixAllScopes()
        {
            return failOnScopes
                ? throw new MissingMethodException(message: "Method not found: 'Void Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationContext..ctor()'.")
                : base.GetSupportedFixAllScopes();
        }
    }

    private sealed class UnresolvedFix(string identifier) : CodeFixProvider
    {
        public int Attempts { get; private set; }

        public override ImmutableArray<string> FixableDiagnosticIds => [identifier];

        public override Task RegisterCodeFixesAsync(CodeFixContext context)
        {
            Attempts++;
            context.RegisterCodeFix(
                CodeAction.Create(
                    title: "Declare the unresolved symbol",
                    cancellationToken => Task.FromResult(context.Document.WithText(SourceText.From(text: "class Example { void Run() { } }")))
                ),
                context.Diagnostics
            );

            return Task.CompletedTask;
        }
    }
}
