using NetAgents.Analyzers.Formatting;
using NetAgents.Analyzers.Tests.Infrastructure;

namespace NetAgents.Analyzers.Tests.Formatting;

/// <summary>
/// Verifies separation of method declarations and preservation of surrounding source.
/// </summary>
public sealed class MethodSpacingTests
{

    /// <summary>
    /// Verifies existing separation and unrelated members are left alone.
    /// </summary>
    [Theory]
    [InlineData("class ExampleType { void Execute() {} }")]
    [InlineData("class ExampleType { void First() {}\n \t\nvoid Second() {} }")]
    [InlineData("class ExampleType { void First() {} int Count; void Second() {} }")]
    [InlineData("// <auto-generated/>\nclass ExampleType { void First() {} void Second() {} }")]
    public async Task AcceptsExistingSeparation(string source)
    {
        Assert.Empty(await AnalyzerTestHarness.Analyze(new MethodSpacingAnalyzer(), source));
    }

    /// <summary>
    /// Verifies constructors, interface methods, and declarations on a shared line.
    /// </summary>
    [Theory]
    [InlineData("class ExampleType { ExampleType() { } void Execute() { } }", "class ExampleType { ExampleType() { }\n\nvoid Execute() { } }")]
    [InlineData("interface ExampleType { void First(); void Second(); }", "interface ExampleType { void First();\n\nvoid Second(); }")]
    [InlineData(
        "class ExampleType\n{\n    void First() {}\n    /* text\n\n       text */\n    void Second() {}\n}",
        "class ExampleType\n{\n    void First() {}\n\n    /* text\n\n       text */\n    void Second() {}\n}"
    )]
    public async Task FixesAdjacentDeclarations(string source, string expected)
    {
        Assert.Equal(expected, await CodeFixTestHarness.FixMethodSpacing(source, fixAll: false));
    }

    /// <summary>
    /// Verifies batch fixes preserve documentation, attributes, and newline style.
    /// </summary>
    /// <param name="newline">The source newline sequence.</param>
    [Theory]
    [InlineData("\n")]
    [InlineData("\r\n")]
    public async Task SeparatesMethods(string newline)
    {
        string source = string.Join(
            newline,
            value: [
            "class ExampleType", "{", "    void First() { }", "    /// <summary>Second.</summary>",
            "    [System.Obsolete]", "    void Second() { }", "    int Third() => 3;", "}"]
        );

        string expected = source.Replace(oldValue: "    ///", newline + "    ///", StringComparison.Ordinal)
            .Replace(oldValue: "    int Third", newline + "    int Third", StringComparison.Ordinal);

        Assert.Equal(expected, await CodeFixTestHarness.FixMethodSpacing(source, fixAll: true));
    }
}
