using System.Globalization;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

using NetAgents.Analyzers.SourceFiles;
using NetAgents.Analyzers.Tests.Infrastructure;

namespace NetAgents.Analyzers.Tests.SourceFiles;

/// <summary>
/// Verifies directory limits, generated-file exclusions, and independent compilation counts.
/// </summary>
public sealed class DirectoryFileCountAnalyzerTests
{
    /// <summary>
    /// Verifies the exact boundary allows sixteen files and rejects the seventeenth.
    /// </summary>
    [Fact]
    public async Task AllowsSixteenFilesAndRejectsSeventeen()
    {
        DirectoryFileCountAnalyzer analyzer = new();
        SyntaxTree[] files = CreateFiles(directory: "Features", count: 17);
        Assert.Empty(await AnalyzerTestHarness.Analyze(analyzer, files.Take(count: 16)));

        Diagnostic diagnostic = Assert.Single(await AnalyzerTestHarness.Analyze(analyzer, files));
        Assert.Equal(DirectoryFileCountAnalyzer.RuleIdentifier, diagnostic.Id);
        Assert.Equal(expected: "Features/Source00.cs", actual: diagnostic.Location.SourceTree?.FilePath);
        Assert.Equal(
            expected: "Directory 'Features' contains 17 authored C# files (maximum 16); organize these files into subdirectories with narrower responsibilities",
            actual: diagnostic.GetMessage(CultureInfo.InvariantCulture)
        );
    }

    /// <summary>
    /// Verifies unnamed trees, non-C# paths, and repeated paths do not inflate the count.
    /// </summary>
    [Fact]
    public async Task CountsOnlyDistinctNamedCSharpFiles()
    {
        SyntaxTree[] files = [.. CreateFiles(directory: "Features", count: 16),
            CSharpSyntaxTree.ParseText(text: ""),
            CSharpSyntaxTree.ParseText(text: "", path: "Features/Notes.txt"),
            CSharpSyntaxTree.ParseText(text: "", path: "Features/Script.csx"),
            CSharpSyntaxTree.ParseText(text: "", path: "Features/Source00.cs"),
            CSharpSyntaxTree.ParseText(text: "", path: "Features\\Source01.cs")];

        Assert.Empty(await AnalyzerTestHarness.Analyze(new DirectoryFileCountAnalyzer(), files));
    }

    /// <summary>
    /// Verifies direct-child counts, rather than a recursive total, determine violations.
    /// </summary>
    [Fact]
    public async Task CountsParentChildAndSiblingDirectoriesSeparately()
    {
        SyntaxTree[] files = [.. CreateFiles(directory: "Features", count: 16),
            .. CreateFiles(directory: "Features/Buying", count: 16), .. CreateFiles(directory: "Features/Selling", count: 16)];

        Assert.Empty(await AnalyzerTestHarness.Analyze(new DirectoryFileCountAnalyzer(), files));
    }

    /// <summary>
    /// Verifies source files at the project root or outside it are still counted.
    /// </summary>
    /// <param name="directory">The physical directory represented by the syntax paths.</param>
    [Theory]
    [InlineData("")]
    [InlineData("../Shared")]
    [InlineData("/workspace/Shared")]
    [InlineData("C:\\workspace\\Shared")]
    public async Task CountsRootAndLinkedFileDirectories(string directory)
    {
        ArgumentNullException.ThrowIfNull(directory);
        Diagnostic diagnostic = Assert.Single(await AnalyzerTestHarness.Analyze(new DirectoryFileCountAnalyzer(), CreateFiles(directory, count: 17)));
        Assert.Equal(DirectoryFileCountAnalyzer.RuleIdentifier, diagnostic.Id);
    }

    /// <summary>
    /// Verifies Roslyn's generated-file recognition excludes generated filenames and headers.
    /// </summary>
    [Fact]
    public async Task ExcludesGeneratedFiles()
    {
        SyntaxTree[] files = [.. CreateFiles(directory: "Features", count: 16),
            CSharpSyntaxTree.ParseText(text: "", path: "Features/Generated.g.cs"),
            CSharpSyntaxTree.ParseText(text: "", path: "Features/Generated.g.i.cs"),
            CSharpSyntaxTree.ParseText(text: "", path: "Features/Generated.designer.cs"),
            CSharpSyntaxTree.ParseText(text: "", path: "Features/Generated.generated.cs"),
            CSharpSyntaxTree.ParseText(text: "// <auto-generated/>\n", path: "Features/GeneratedHeader.cs")];

        Assert.Empty(await AnalyzerTestHarness.Analyze(new DirectoryFileCountAnalyzer(), files));
    }

    /// <summary>
    /// Verifies an analyzer instance never carries file counts from one project into another.
    /// </summary>
    [Fact]
    public async Task KeepsCompilationStateIsolated()
    {
        DirectoryFileCountAnalyzer analyzer = new();
        Diagnostic oversized = Assert.Single(await AnalyzerTestHarness.Analyze(analyzer, CreateFiles(directory: "Features", count: 17)));
        Assert.Equal(DirectoryFileCountAnalyzer.RuleIdentifier, oversized.Id);
        Assert.Empty(await AnalyzerTestHarness.Analyze(analyzer, CreateFiles(directory: "Features", count: 16)));
    }

    /// <summary>
    /// Verifies source pragmas cannot disable this structural requirement.
    /// </summary>
    [Fact]
    public async Task RejectsSuppression()
    {
        SyntaxTree[] files = [.. Enumerable.Range(start: 0, count: 17).Select(
            static index =>
            CSharpSyntaxTree.ParseText(
                text: "#pragma warning disable NETAGENTS0018\n",
                path: "Features/Source" + index.ToString(format: "D2", CultureInfo.InvariantCulture) + ".cs"
            )
        )];

        Diagnostic diagnostic = Assert.Single(await AnalyzerTestHarness.Analyze(new DirectoryFileCountAnalyzer(), files));
        Assert.Equal(DirectoryFileCountAnalyzer.RuleIdentifier, diagnostic.Id);
        Assert.False(diagnostic.IsSuppressed);
    }

    /// <summary>
    /// Verifies each oversized directory produces one stable diagnostic regardless of tree order.
    /// </summary>
    [Fact]
    public async Task ReportsEachOversizedDirectoryOnce()
    {
        SyntaxTree[] files = [.. CreateFiles(directory: "Features/Buying", count: 17), .. CreateFiles(directory: "Features/Selling", count: 20)];
        Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(new DirectoryFileCountAnalyzer(), files.Reverse());
        Assert.Equal(expected: 2, actual: diagnostics.Length);
        Assert.Contains(diagnostics, static diagnostic => diagnostic.Location.SourceTree?.FilePath == "Features/Buying/Source00.cs");
        Assert.Contains(diagnostics, static diagnostic => diagnostic.Location.SourceTree?.FilePath == "Features/Selling/Source00.cs");
    }

    private static SyntaxTree[] CreateFiles(string directory, int count)
    {
        string prefix = directory.Length == 0 ? string.Empty : directory + "/";

        return [.. Enumerable.Range(start: 0, count).Select(
            index => CSharpSyntaxTree.ParseText(text: "// Authored source.\n", path: prefix + "Source" + index.ToString(format: "D2", CultureInfo.InvariantCulture) + ".cs")
        )];
    }
}
