using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using NetAgents.Analyzers.Ordering;
using NetAgents.Analyzers.Tests.Infrastructure;

namespace NetAgents.Analyzers.Tests.Ordering;

/// <summary>
/// Verifies stable ordering and preservation of executable initialization.
/// </summary>
public sealed class MemberOrderingTests
{

    /// <summary>
    /// Verifies directive boundaries, existing order, and generated files are respected.
    /// </summary>
    [Theory]
    [InlineData("class ExampleType { void Alpha() {} void Zebra() {} }")]
    [InlineData("class ExampleType {\n#region Methods\nvoid Zebra() {}\nvoid Alpha() {}\n#endregion\n}")]
    [InlineData("// <auto-generated/>\nclass ExampleType { void Zebra() {} void Alpha() {} }")]
    [InlineData("struct ExampleType { public int Zebra; public int Alpha; }")]
    [InlineData("class ExampleType { private static int Zebra = 1; public static int Alpha = Zebra; }")]
    public async Task AcceptsPreservedOrder(string source)
    {
        Assert.Empty(await AnalyzerTestHarness.Analyze(new MemberOrderingAnalyzer(), source));
    }

    /// <summary>
    /// Verifies nested types and multiple types can be fixed together.
    /// </summary>
    [Fact]
    public async Task FixesNestedTypes()
    {
        const string source = "class ExampleType { class Nested { void Zebra() {} void Alpha() {} } void Zebra() {} void Alpha() {} } class OtherType { void Zebra() {} void Alpha() {} }";
        string fixedSource = await CodeFixTestHarness.FixMemberOrdering(source, fixAll: true);

        Assert.Empty(await AnalyzerTestHarness.Analyze(new MemberOrderingAnalyzer(), fixedSource));
    }

    /// <summary>
    /// Verifies comments and attributes travel with sorted declarations.
    /// </summary>
    [Fact]
    public async Task PreservesDocumentation()
    {
        const string source = "class ExampleType\r\n{\r\n    void Zebra() {} // zebra\r\n    /// <summary>Alpha.</summary>\r\n    [System.Obsolete]\r\n    void Alpha() {}\r\n}";
        const string expected = "class ExampleType\r\n{\r\n    /// <summary>Alpha.</summary>\r\n    [System.Obsolete]\r\n    void Alpha() {}\r\n    void Zebra() {} // zebra\r\n}";

        Assert.Equal(expected, await CodeFixTestHarness.FixMemberOrdering(source, fixAll: false));
    }

    /// <summary>
    /// Verifies initializers retain their order across member kinds.
    /// </summary>
    [Fact]
    public async Task PreservesInitializationOrder()
    {
        const string source = """
            class ExampleType
            {
                private static int Zebra = Next();
                public static int Middle { get; } = Next();
                public static int Alpha = Next();
                private static int Next() => 1;
                public void ZebraMethod() { }
                public void AlphaMethod() { }
            }
            """;

        string fixedSource = await CodeFixTestHarness.FixMemberOrdering(source, fixAll: true);
        TypeDeclarationSyntax declaration = (await CSharpSyntaxTree.ParseText(fixedSource).GetRootAsync()).DescendantNodes().OfType<TypeDeclarationSyntax>().First();
        MemberDeclarationSyntax[] members = [.. declaration.Members];
        string[] initializers = [.. members.Where(static member => member is FieldDeclarationSyntax or PropertyDeclarationSyntax).Select(static member => member.ToString())];

        Assert.Contains(expectedSubstring: "Zebra", initializers[0], StringComparison.Ordinal);
        Assert.Contains(expectedSubstring: "Middle", initializers[1], StringComparison.Ordinal);
        Assert.Contains(expectedSubstring: "Alpha", initializers[2], StringComparison.Ordinal);
        Assert.Empty(await AnalyzerTestHarness.Analyze(new MemberOrderingAnalyzer(), fixedSource));
    }

    /// <summary>
    /// Verifies member kind, accessibility, storage, and alphabetical ordering.
    /// </summary>
    [Fact]
    public async Task SortsMembers()
    {
        const string source = """
            class ExampleType
            {
                private class ZebraNested { }
                public void Zebra() { }
                private int privateField;
                public int instanceField;
                public static int staticField;
                public const int Constant = 1;
                public void Alpha() { }
                public static void StaticMethod() { }
                internal void InternalMethod() { }
                protected internal void ProtectedInternalMethod() { }
                protected void ProtectedMethod() { }
                private protected void PrivateProtectedMethod() { }
                private void PrivateMethod() { }
                public readonly int ReadonlyField;
                public ExampleType() { }
                public int Property => 1;
                public class AlphaNested { }
            }
            """;

        const string expected = """
            class ExampleType
            {
                public const int Constant = 1;
                public static int staticField;
                public readonly int ReadonlyField;
                public int instanceField;
                private int privateField;
                public ExampleType() { }
                public int Property => 1;
                public static void StaticMethod() { }
                public void Alpha() { }
                public void Zebra() { }
                internal void InternalMethod() { }
                protected internal void ProtectedInternalMethod() { }
                protected void ProtectedMethod() { }
                private protected void PrivateProtectedMethod() { }
                private void PrivateMethod() { }
                public class AlphaNested { }
                private class ZebraNested { }
            }
            """;

        Assert.Equal(expected, await CodeFixTestHarness.FixMemberOrdering(source, fixAll: true));
    }
}
