using System.Collections.Concurrent;
using System.Collections.Immutable;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CodeActions;
using Microsoft.CodeAnalysis.CodeFixes;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Formatting;
using Microsoft.CodeAnalysis.Rename;
using Microsoft.CodeAnalysis.Text;

namespace NetAgents.BuildTasks;

internal static class CodeFixRunner
{
    private static readonly string[] GeneratedSuffixes = [".g.cs", ".g.i.cs", ".generated.cs", ".designer.cs"];

    // Roslyn answers these errors with generate-variable, generate-method, and generate-type fixes.
    // Declaring API the author never wrote is not formatting, so an unresolved symbol stays a compiler error.
    private static readonly string[] UnresolvedSymbolErrors =
        ["CS0103", "CS0117", "CS0120", "CS0234", "CS0246", "CS0426", "CS1061", "CS7036"];

    public static async Task<CodeFixResult> Fix(
        Project project,
        ImmutableArray<DiagnosticAnalyzer> analyzers,
        CodeFixProvider[] providers,
        Action<string> reportAnalyzerFault,
        CancellationToken cancellationToken
    )
    {
        ConcurrentDictionary<string, bool> reported = new(StringComparer.Ordinal);

        // Without a handler an analyzer that throws becomes an AD0001 this compilation escalates to an
        // error nothing can fix, and a hosted analyzer built for a newer Roslyn is where that happens.
        // Every pass of the loop below analyzes again, so an identical fault is announced once.
        void OnAnalyzerException(Exception exception, DiagnosticAnalyzer analyzer, Diagnostic diagnostic)
        {
            string fault = $"NetAgents cannot run the {analyzer.GetType().FullName} analyzer ({diagnostic.Id}): {exception.Message}";

            if (reported.TryAdd(fault, value: true))
                reportAnalyzerFault(fault);
        }

        ImmutableHashSet<DocumentId> editable = [];

        foreach (Document document in project.Documents)
        {
            SourceText source = await document.GetTextAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            string header = source.ToString(new TextSpan(start: 0, Math.Min(source.Length, val2: 1024)));

            // Both spellings and suffixes match Roslyn's own generated-code detection, so the
            // formatter skips exactly the files the analyzers already refuse to look at.
            bool generated = GeneratedSuffixes.Any(suffix => document.Name.EndsWith(suffix, StringComparison.OrdinalIgnoreCase))
                || header.Contains(value: "<auto-generated", StringComparison.OrdinalIgnoreCase)
                || header.Contains(value: "<autogenerated", StringComparison.OrdinalIgnoreCase);

            if (!generated)
                editable = editable.Add(document.Id);
        }

        HashSet<string> states = [];
        string? attempt = null;

        while (!cancellationToken.IsCancellationRequested)
        {
            cancellationToken.ThrowIfCancellationRequested();
            project = await FormatWhitespace(project, editable, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);

            ImmutableArray<Diagnostic> diagnostics = await GetAllDiagnostics(project, analyzers, OnAnalyzerException, cancellationToken)
                .ConfigureAwait(continueOnCapturedContext: false);

            StringBuilder state = new();

            foreach (Document document in project.Documents)
            {
                SourceText text = await document.GetTextAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                state = state.Append(document.Id).Append(value: ':').Append(text.Length).Append(value: ':').Append(text);
            }

            string fingerprint = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(state.ToString())));

            if (!states.Add(fingerprint))
                throw Failure(reason: "repeated a project state without stabilizing", attempt, diagnostics);

            CodeActionApplication application = await ApplyAvailableFix(project, diagnostics, analyzers, providers, editable, OnAnalyzerException, cancellationToken)
                .ConfigureAwait(continueOnCapturedContext: false);

            attempt = application.Attempt;

            if (application.Project is null)
            {
                if (attempt is not null)
                    throw Failure(reason: "made no progress", attempt, diagnostics);

                // Compilation reports these from the rewritten files, so the caller can name what it wrote.
                // Only source locations qualify: the formatter escalates every diagnostic to an error,
                // including reference remarks the consumer build never fails for.
                return new(project, [.. diagnostics.Where(IsBlockingError)]);
            }

            project = application.Project;
        }

        cancellationToken.ThrowIfCancellationRequested();

        throw new InvalidOperationException(message: "The formatting operation ended without completing.");
    }

    private static async Task<CodeActionApplication> ApplyAvailableFix(
        Project project,
        ImmutableArray<Diagnostic> diagnostics,
        ImmutableArray<DiagnosticAnalyzer> analyzers,
        CodeFixProvider[] providers,
        ImmutableHashSet<DocumentId> editable,
        Action<Exception, DiagnosticAnalyzer, Diagnostic> onAnalyzerException,
        CancellationToken cancellationToken
    )
    {
        string? attempt = null;
        HashSet<string> rejectedFixAllActions = [];

        CodeActionApplication collision = await AvoidNamingCollisions(project, diagnostics, editable, cancellationToken)
            .ConfigureAwait(continueOnCapturedContext: false);

        if (collision.Project is not null)
        {
            Project renamed = await ReparseChangedDocuments(project, collision.Project, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);

            ImmutableArray<Diagnostic> renameErrors = await GetIntroducedErrors(renamed, diagnostics, analyzers, onAnalyzerException, cancellationToken)
                .ConfigureAwait(continueOnCapturedContext: false);

            ImmutableArray<Diagnostic> renameCompilerErrors = [.. renameErrors.Where(IsCompilerError)];

            return renameCompilerErrors.IsEmpty
                ? new(renamed, collision.Attempt)
                : throw Failure(reason: "introduced compiler errors", collision.Attempt, renameCompilerErrors);
        }

        // A total order keeps the chosen fix identical across runs despite parallel analyzer output.
        IOrderedEnumerable<Diagnostic> ordered = diagnostics.ToArray().OrderBy(static diagnostic => diagnostic.Id, StringComparer.Ordinal)
            .ThenBy(static diagnostic => diagnostic.Location.SourceTree?.FilePath ?? string.Empty, StringComparer.Ordinal)
            .ThenBy(static diagnostic => diagnostic.Location.SourceSpan.Start);

        foreach (Diagnostic diagnostic in ordered)
        {
            Document? document = diagnostic.Location.SourceTree is null ? null : project.GetDocument(diagnostic.Location.SourceTree);

            if (document is null || !editable.Contains(document.Id) || diagnostic.IsSuppressed)
                continue;

            // Every fix offered for these errors invents a declaration, so the compiler reports them untouched.
            if (UnresolvedSymbolErrors.Contains(diagnostic.Id, StringComparer.Ordinal))
                continue;

            foreach (CodeFixProvider provider in providers.Where(provider => CanFixDiagnostic(provider, diagnostic)))
            {
                List<CodeAction> actions = await GetCodeActions(provider, document, diagnostic, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);

                foreach (CodeAction action in actions)
                {
                    CodeAction selected = action;

                    while (!selected.NestedActions.IsEmpty)
                        selected = selected.NestedActions[index: 0];

                    FixAllProvider? fixAllProvider = GetProjectFixAllProvider(provider);
                    bool canFixProject = fixAllProvider is not null && selected.EquivalenceKey is not null;

                    string? fixAllKey = canFixProject
                        ? $"{provider.GetType().FullName}|{selected.EquivalenceKey}"
                        : null;

                    if (fixAllKey is not null && rejectedFixAllActions.Contains(fixAllKey))
                        continue;

                    CodeAction preferred = selected;

                    if (canFixProject && fixAllProvider is not null)
                    {
                        preferred = await GetFixAllAction(provider, fixAllProvider, document, selected, diagnostics, cancellationToken)
                            .ConfigureAwait(continueOnCapturedContext: false) ?? selected;
                    }

                    ImmutableArray<CodeActionOperation> operations = await GetOperations(preferred, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);

                    // A project-wide action computes its edits here too, and one that fails must not take
                    // the single document's repair down with it.
                    if (operations.IsEmpty && !ReferenceEquals(preferred, selected))
                    {
                        preferred = selected;
                        operations = await GetOperations(selected, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                    }

                    ApplyChangesOperation? change = operations.OfType<ApplyChangesOperation>().FirstOrDefault();
                    Project? updated = change?.ChangedSolution.GetProject(project.Id);

                    if (updated is null)
                        continue;

                    ProjectChanges differences = updated.GetChanges(project);
                    DocumentId[] changedDocuments = [.. differences.GetChangedDocuments()];

                    bool supported = changedDocuments.All(editable.Contains)
                        && !differences.GetAddedDocuments().Any() && !differences.GetRemovedDocuments().Any();

                    if (!supported)
                        continue;

                    string description = $"{diagnostic} — code action '{preferred.Title}'";

                    // Only a diagnostic that still fails the build explains a run that stopped. An action
                    // offered for a suggestion is dropped below, so naming it would blame an unrelated rule.
                    if (diagnostic.Severity == DiagnosticSeverity.Error)
                        attempt = description;

                    // Comparing text first keeps an action that rewrites nothing off the analyzer path.
                    if (!await HasTextChanges(project, updated, changedDocuments, cancellationToken).ConfigureAwait(continueOnCapturedContext: false))
                        continue;

                    updated = await ReparseChangedDocuments(project, updated, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);

                    ImmutableArray<Diagnostic> introducedErrors = await GetIntroducedErrors(updated, diagnostics, analyzers, onAnalyzerException, cancellationToken)
                        .ConfigureAwait(continueOnCapturedContext: false);

                    ImmutableArray<Diagnostic> introducedCompilerErrors = [.. introducedErrors.Where(IsCompilerError)];

                    // A hidden or info diagnostic is a suggestion the compiler never fails for, so a broken
                    // action offered for one is dropped below instead of taking an otherwise clean build down.
                    bool optional = diagnostic.Severity < DiagnosticSeverity.Warning;

                    if (!introducedCompilerErrors.IsEmpty && !optional)
                        throw Failure(reason: "introduced compiler errors", description, introducedCompilerErrors);

                    // An error already fails the build, so only lower severities must avoid new analyzer errors.
                    if (diagnostic.Severity != DiagnosticSeverity.Error && !introducedErrors.IsEmpty)
                    {
                        if (fixAllKey is not null && !rejectedFixAllActions.Add(fixAllKey))
                            throw new InvalidOperationException(message: "The rejected formatting action was already recorded.");

                        continue;
                    }

                    return new(updated, description);
                }
            }
        }

        return new(Project: null, attempt);
    }

    private static async Task<Project?> AvoidNamingCollision(Document document, TextSpan diagnosticSpan, CancellationToken cancellationToken)
    {
        SyntaxNode root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false)
            ?? throw new InvalidOperationException(message: "The naming document has no syntax root.");

        SemanticModel model = await document.GetSemanticModelAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false)
            ?? throw new InvalidOperationException(message: "The naming document has no semantic model.");

        if (model.GetDeclaredSymbol(root.FindNode(diagnosticSpan), cancellationToken) is not ILocalSymbol local)
            return null;

        // ponytail: handles case-only collisions; extend the comparison if other naming transformations need repair.
        bool collision = model.LookupSymbols(diagnosticSpan.Start).Any(
            symbol =>
            symbol is ILocalSymbol or IParameterSymbol && !SymbolEqualityComparer.Default.Equals(symbol, local)
                && string.Equals(symbol.Name, local.Name, StringComparison.OrdinalIgnoreCase)
        );

        if (!collision)
            return null;

        HashSet<string> identifiers = root.DescendantTokens().Where(static token => token.IsKind(SyntaxKind.IdentifierToken))
            .Select(static token => token.ValueText).ToHashSet(StringComparer.OrdinalIgnoreCase);

        string name = local.Name + "Value";

        while (identifiers.Contains(name))
            name += "Value";

        Solution renamed = await Renamer.RenameSymbolAsync(document.Project.Solution, local, new SymbolRenameOptions(), name, cancellationToken)
            .ConfigureAwait(continueOnCapturedContext: false);

        return renamed.GetProject(document.Project.Id);
    }

    private static async Task<CodeActionApplication> AvoidNamingCollisions(
        Project project,
        ImmutableArray<Diagnostic> diagnostics,
        ImmutableHashSet<DocumentId> editable,
        CancellationToken cancellationToken
    )
    {
        List<(DocumentId Document, TextSpan SourceSpan, Diagnostic Diagnostic)> candidates = [];

        foreach (Diagnostic diagnostic in diagnostics)
        {
            Document? document = diagnostic.Id == "IDE1006" && diagnostic.Location.SourceTree is not null
                ? project.GetDocument(diagnostic.Location.SourceTree)
                : null;

            if (document is not null && editable.Contains(document.Id))
                candidates.Add((document.Id, diagnostic.Location.SourceSpan, diagnostic));
        }

        Project updated = project;
        Diagnostic? first = null;

        foreach (
            (DocumentId Document, TextSpan SourceSpan, Diagnostic Diagnostic) candidate in candidates
                .OrderBy(static candidate => candidate.Document.Id)
                .ThenByDescending(static candidate => candidate.SourceSpan.Start)
        )
        {
            Document document = updated.GetDocument(candidate.Document) ?? throw new InvalidOperationException(message: "The naming document is missing.");
            Project? renamed = await AvoidNamingCollision(document, candidate.SourceSpan, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);

            if (renamed is null)
                continue;

            updated = renamed;
            first ??= candidate.Diagnostic;
        }

        return first is null
            ? new(Project: null, Attempt: null)
            : new(updated, $"{first} — rename colliding locals before applying naming-style fixes");
    }

    private static bool CanFixDiagnostic(CodeFixProvider provider, Diagnostic diagnostic)
    {
        try
        {
            return provider.FixableDiagnosticIds.Contains(diagnostic.Id, StringComparer.Ordinal);
        }
        catch (Exception exception) when (exception is not OperationCanceledException)
        {
            // A provider compiled against another Roslyn version can fail to even list its identifiers.
            return false;
        }
    }

    private static DiagnosticIdentity ErrorKey(Diagnostic diagnostic)
    {
        return new(diagnostic.Id, diagnostic.GetMessage(CultureInfo.InvariantCulture), diagnostic.Location.SourceTree?.FilePath ?? string.Empty);
    }

    private static InvalidOperationException Failure(string reason, string? attempt, ImmutableArray<Diagnostic> diagnostics)
    {
        List<string> lines = [$"Automatic formatting {reason}."];

        if (attempt is not null)
            lines.Add("Attempted code action: " + attempt);

        // Oscillating analyzer fixes are the usual cause, so every blocking error is listed, not just
        // compiler errors. The formatting compilation escalates everything, so only in-source errors
        // qualify: reference remarks the consumer build never fails for would bury the real blockers.
        lines.AddRange(
            diagnostics.Where(IsBlockingError)
                .OrderBy(static diagnostic => diagnostic.Location.SourceTree?.FilePath ?? string.Empty, StringComparer.Ordinal)
                .ThenBy(static diagnostic => diagnostic.Location.SourceSpan.Start)
                .Select(static diagnostic => diagnostic.ToString())
        );

        // An empty segment would reach MSBuild as a second error with no message at all.
        return new InvalidOperationException(string.Join(Environment.NewLine, lines));
    }

    private static async Task<Project> FormatWhitespace(Project project, ImmutableHashSet<DocumentId> editable, CancellationToken cancellationToken)
    {
        foreach (DocumentId identifier in editable)
        {
            Document document = project.GetDocument(identifier) ?? throw new InvalidOperationException(message: "A formatting document is missing.");
            Document formatted = await Formatter.FormatAsync(document, cancellationToken: cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            SourceText text = await formatted.GetTextAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            SyntaxTree? tree = await formatted.GetSyntaxTreeAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            AnalyzerConfigOptions options = project.AnalyzerOptions.AnalyzerConfigOptionsProvider.GetOptions(tree ?? throw new InvalidOperationException(message: "A syntax tree is missing."));

            bool needsFinalNewline = text.Length > 0 && text.Lines.GetLineFromPosition(text.Length).Span.Length > 0
                && options.TryGetValue(key: "insert_final_newline", out string? finalNewline) && finalNewline == "true";

            if (needsFinalNewline)
                formatted = formatted.WithText(text.WithChanges(new TextChange(new TextSpan(text.Length, length: 0), GetLineEnding(text, options))));

            project = formatted.Project;
        }

        return project;
    }

    private static async Task<ImmutableArray<Diagnostic>> GetAllDiagnostics(
        Project project,
        ImmutableArray<DiagnosticAnalyzer> analyzers,
        Action<Exception, DiagnosticAnalyzer, Diagnostic> onAnalyzerException,
        CancellationToken cancellationToken
    )
    {
        Compilation compilation = await project.GetCompilationAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false)
            ?? throw new InvalidOperationException(message: "The formatting compilation is unavailable.");

        CompilationWithAnalyzersOptions options = new(project.AnalyzerOptions, onAnalyzerException, concurrentAnalysis: true, logAnalyzerExecutionTime: false);

        return await compilation.WithAnalyzers(analyzers, options).GetAllDiagnosticsAsync(cancellationToken)
            .ConfigureAwait(continueOnCapturedContext: false);
    }

    private static async Task<List<CodeAction>> GetCodeActions(CodeFixProvider provider, Document document, Diagnostic diagnostic, CancellationToken cancellationToken)
    {
        List<CodeAction> actions = [];

        try
        {
            CodeFixContext context = new(document, diagnostic, (action, associatedDiagnostics) => actions.Add(action), cancellationToken);
            await provider.RegisterCodeFixesAsync(context).ConfigureAwait(continueOnCapturedContext: false);
        }
        catch (Exception exception) when (exception is not OperationCanceledException)
        {
            // Registration that fails part way leaves an arbitrary subset, so the whole provider is skipped.
            return [];
        }

        return actions;
    }

    private static async Task<CodeAction?> GetFixAllAction(
        CodeFixProvider provider,
        FixAllProvider fixAllProvider,
        Document document,
        CodeAction selected,
        ImmutableArray<Diagnostic> diagnostics,
        CancellationToken cancellationToken
    )
    {
        try
        {
            FixAllContext context = new(
                document,
                provider,
                FixAllScope.Project,
                selected.EquivalenceKey,
                [.. provider.FixableDiagnosticIds],
                new BuildDiagnostics(diagnostics),
                cancellationToken
            );

            return await fixAllProvider.GetFixAsync(context).ConfigureAwait(continueOnCapturedContext: false);
        }
        catch (Exception exception) when (exception is not OperationCanceledException)
        {
            // A failed project-wide fix still leaves the single-document action, which the caller validates.
            return null;
        }
    }

    private static async Task<ImmutableArray<Diagnostic>> GetIntroducedErrors(
        Project after,
        ImmutableArray<Diagnostic> beforeDiagnostics,
        ImmutableArray<DiagnosticAnalyzer> analyzers,
        Action<Exception, DiagnosticAnalyzer, Diagnostic> onAnalyzerException,
        CancellationToken cancellationToken
    )
    {
        ImmutableArray<Diagnostic> afterDiagnostics = await GetAllDiagnostics(after, analyzers, onAnalyzerException, cancellationToken)
            .ConfigureAwait(continueOnCapturedContext: false);

        Dictionary<DiagnosticIdentity, int> existingErrors = beforeDiagnostics
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .CountBy(ErrorKey).ToDictionary();

        return [.. afterDiagnostics
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .GroupBy(ErrorKey)
            .SelectMany(group => group.Skip(existingErrors.GetValueOrDefault(group.Key)))];
    }

    private static string GetLineEnding(SourceText text, AnalyzerConfigOptions options)
    {
        if (options.TryGetValue(key: "end_of_line", out string? configured))
            return configured switch { "crlf" => "\r\n", "cr" => "\r", _ => "\n" };

        // Without a configured value, appending anything else would mix endings within one file.
        foreach (TextLine line in text.Lines)
        {
            if (line.EndIncludingLineBreak > line.End)
                return text.ToString(TextSpan.FromBounds(line.End, line.EndIncludingLineBreak));
        }

        return "\n";
    }

    private static async Task<ImmutableArray<CodeActionOperation>> GetOperations(CodeAction action, CancellationToken cancellationToken)
    {
        try
        {
            return await action.GetOperationsAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        catch (Exception exception) when (exception is not OperationCanceledException)
        {
            // A lazy code action computes its edits here, which is where version skew usually throws.
            return [];
        }
    }

    private static FixAllProvider? GetProjectFixAllProvider(CodeFixProvider provider)
    {
        try
        {
            FixAllProvider? fixAllProvider = provider.GetFixAllProvider();
            bool supportsProject = fixAllProvider is not null && fixAllProvider.GetSupportedFixAllScopes().Contains(FixAllScope.Project);

            return supportsProject ? fixAllProvider : null;
        }
        catch (Exception exception) when (exception is not OperationCanceledException)
        {
            // A provider that cannot describe its Fix all support is treated as offering none.
            return null;
        }
    }

    private static async Task<bool> HasTextChanges(Project before, Project after, DocumentId[] changedDocuments, CancellationToken cancellationToken)
    {
        foreach (DocumentId identifier in changedDocuments)
        {
            Document beforeDocument = before.GetDocument(identifier) ?? throw new InvalidOperationException(message: "The original document is missing.");
            Document afterDocument = after.GetDocument(identifier) ?? throw new InvalidOperationException(message: "The updated document is missing.");
            SourceText beforeText = await beforeDocument.GetTextAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            SourceText afterText = await afterDocument.GetTextAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);

            if (!beforeText.ContentEquals(afterText))
                return true;
        }

        return false;
    }

    private static bool IsBlockingError(Diagnostic diagnostic)
    {
        return diagnostic.Severity == DiagnosticSeverity.Error && diagnostic.Location.IsInSource;
    }

    private static bool IsCompilerError(Diagnostic diagnostic)
    {
        return diagnostic.Id.StartsWith(value: "CS", StringComparison.Ordinal);
    }

    private static async Task<Project> ReparseChangedDocuments(Project before, Project after, CancellationToken cancellationToken)
    {
        foreach (DocumentId identifier in after.GetChanges(before).GetChangedDocuments())
        {
            Document document = after.GetDocument(identifier) ?? throw new InvalidOperationException(message: "The updated document is missing.");
            SourceText text = await document.GetTextAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            after = document.WithText(SourceText.From(text.ToString(), text.Encoding, text.ChecksumAlgorithm)).Project;
        }

        return after;
    }

    private readonly record struct DiagnosticIdentity(string Identifier, string Message, string Path);

    internal sealed record CodeFixResult(Project Project, ImmutableArray<Diagnostic> Blocking);

    private sealed record CodeActionApplication(Project? Project, string? Attempt);
}
