using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;

using NetAgents.Analyzers.Tests.Infrastructure;
using NetAgents.Analyzers.TypeSafety;

namespace NetAgents.Analyzers.Tests.TypeSafety;

/// <summary>
/// Verifies null suppression is rejected regardless of its expression context.
/// </summary>
public sealed class NullForgivingOperatorAnalyzerTests
{
    /// <summary>
    /// Verifies logical operators and generated source remain outside the rule.
    /// </summary>
    /// <param name="source">The source to analyze.</param>
    [Theory]
    [InlineData("class ExampleType { bool Check(bool value) => !value; }")]
    [InlineData("class ExampleType { bool Check(string? value) => value != null; }")]
    [InlineData("// <auto-generated/>\nclass ExampleType { string Value = null!; }")]
    public async Task AllowsOtherOperatorsAndGeneratedSource(string source)
    {
        Assert.Empty(await AnalyzerTestHarness.Analyze(new NullForgivingOperatorAnalyzer(), source));
    }

    /// <summary>
    /// Verifies every suppression expression is reported as a build error.
    /// </summary>
    /// <param name="member">The type member containing null suppression.</param>
    [Theory]
    [InlineData("string value = null!;")]
    [InlineData("static string value = default!;")]
    [InlineData("string Value { get; set; } = null!;")]
    [InlineData("string Value => null!;")]
    [InlineData("string Value { get { return null!; } }")]
    [InlineData("string Read(string? value) => value!;")]
    [InlineData("string Read() { return null!; }")]
    [InlineData("void Execute(string? value) { string result = value!; }")]
    [InlineData("void Execute(string? value) { value = value!; }")]
    [InlineData("void Execute(string? variable) { Test(variable!); } void Test(string value) { }")]
    [InlineData("void Execute(string? value) { System.Console.WriteLine(value!); }")]
    [InlineData("object Create() => new System.Exception(null!);")]
    [InlineData("int Read(string? value) => value!.Length;")]
    [InlineData("char Read(string? value) => value![0];")]
    [InlineData("bool Check(string? value) { if (value!.Length > 0) return true; return false; }")]
    [InlineData("void Execute(string? value) { while (value!.Length > 0) break; }")]
    [InlineData("void Execute(string? value) { do { } while (value!.Length > 0); }")]
    [InlineData("void Execute(string? value) { for (; value!.Length > 0;) break; }")]
    [InlineData("void Execute(string[]? values) { foreach (string value in values!) { } }")]
    [InlineData("string Read(bool condition) => condition ? null! : string.Empty;")]
    [InlineData("string Read(int value) => value switch { _ => null! };")]
    [InlineData("System.Func<string> Create() => () => null!;")]
    [InlineData("System.Func<string> Create() => delegate { return null!; };")]
    [InlineData("void Execute() { string Read() => null!; }")]
    [InlineData("async System.Threading.Tasks.Task Execute(System.Threading.Tasks.Task? pending) { await pending!; }")]
    [InlineData("System.Collections.Generic.IEnumerable<string> Read() { yield return null!; }")]
    [InlineData("string[] Read() => [null!];")]
    [InlineData("string[] Read() => new[] { null! as string };")]
    [InlineData("(string, int) Read() => (null!, 1);")]
    [InlineData("object Read() => new { Value = null! as string };")]
    [InlineData("void Execute(System.IDisposable? value) { using (value!) { } }")]
    [InlineData("void Execute(object? value) { lock (value!) { } }")]
    [InlineData("void Execute(System.Exception? value) { throw value!; }")]
    [InlineData("void Execute(string? value) { try { } catch when (value!.Length > 0) { } }")]
    [InlineData("class NestedType { string Value => null!; }")]
    [InlineData("string Read<TValue>(TValue value) => value!.ToString();")]
    [InlineData("string value = null!; ExampleType() : this(null!) { } ExampleType(string value) { }")]
    public async Task RejectsSuppressionInEveryContext(string member)
    {
        string source = "#nullable enable\nclass ExampleType { " + member + " }";
        Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(new NullForgivingOperatorAnalyzer(), source);
        int expectedCount = member.Count(static character => character == '!');

        Assert.Equal(expectedCount, diagnostics.Length);
        Assert.All(
            diagnostics,
            static diagnostic =>
        {
            Assert.Equal(NullForgivingOperatorAnalyzer.RuleIdentifier, diagnostic.Id);
            Assert.Equal(DiagnosticSeverity.Error, diagnostic.Severity);
        }
        );
    }

    /// <summary>
    /// Verifies top-level arguments are rejected in an executable compilation.
    /// </summary>
    [Fact]
    public async Task RejectsTopLevelArguments()
    {
        const string source = "string variable = null!; Test(variable!); void Test(string value) { }";

        CSharpCompilation compilation = CSharpCompilation.Create(
            assemblyName: "ExampleApplication",
            [CSharpSyntaxTree.ParseText(source)],
            AnalyzerTestHarness.References,
            new CSharpCompilationOptions(OutputKind.ConsoleApplication)
        );

        Assert.Empty(compilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
        Diagnostic[] diagnostics = [.. await compilation.WithAnalyzers([new NullForgivingOperatorAnalyzer()]).GetAnalyzerDiagnosticsAsync()];

        Assert.Equal(expected: 2, diagnostics.Length);
        Assert.All(diagnostics, static diagnostic => Assert.Equal(NullForgivingOperatorAnalyzer.RuleIdentifier, diagnostic.Id));
    }

    /// <summary>
    /// Verifies nested suppression nodes and top-level statements are all diagnosed.
    /// </summary>
    [Fact]
    public async Task ReportsEveryOccurrence()
    {
        const string source = "class ExampleType { string Read(string? value) => value!.Trim()!; }";
        const int expectedCount = 2;
        Diagnostic[] diagnostics = await AnalyzerTestHarness.Analyze(new NullForgivingOperatorAnalyzer(), source);

        Assert.Equal(expectedCount, diagnostics.Length);
        Assert.All(diagnostics, static diagnostic => Assert.Equal(NullForgivingOperatorAnalyzer.RuleIdentifier, diagnostic.Id));
    }
}
